### PR TITLE
WIP: Add an Emscripten port

### PR DESCRIPTION
**Pull request by whitequark**
## Overview

The purpose of this pull request is to give some visibility to the Emscripten port that has so far quietly existed as a branch. Its status is **an early preview**; enough things work that it demonstrates the concept is sound, but it cannot be used for anything useful yet. [Try it out!](https://files.whitequark.org/SolveSpace/solvespace.html)

Other than the issues listed below, everything works to my knowledge, and it's reasonably fast. If you encounter a bug not listed, or pathological slowness, please report it in a comment.

## Known issues

The major missing features are:
  - [x] Tooltips are not implemented.
  - [x] Preferences are not saved.
  - [ ] Any way to open or save files. This is particularly bad because of the way SolveSpace handles assemblies. It is likely that #75 will be required before this port is usable in any meaningful way.
  - [ ] Some message dialogs (the ones that require a choice, specifically) are written in a blocking style and ~need to be~ may be rewritten with callbacks. It is also possible to use "new Asyncify" as of 2020, and might be preferable to do so.
  - [ ] There's no way to move the "split" between main window and property browser.
  - [ ] Scrollbars are not implemented, so there's no way to scroll the property browser.

The following are known bugs:
  - [x] Menu mnemonics are broken, the Alt+... hotkeys don't trigger them. No idea why.
  - [x] Pressing Esc does not dismiss message dialogs.
  - [x] Pressing Esc while editing a property also invokes the Esc keybinding, changing the open page in the property browser.
  - [ ] Fullscreen is broken. The browser hard-stretches the entire canvas over the entire screen, ignoring element sizing. This is apparently required by the spec?

Additionally, there are some Firefox-specific issues:
  - [ ] Fractional devicePixelRatio factors don't work (result in broken rendering).
  - [ ] Something about the styling and/or \<canvas\> doesn't work the same, and the canvas is stretched vertically under the menu.
  - [ ] Shift-RMB cannot be used to rotate the sketch as that is hardcoded to bring up the browser menu, as a security feature. (It still rotates but the menu is in the way and input handling code can get confused.)

## Working on the port

The missing features can all be quickly located in the codebase by searching for the regex `FIXME\((async|emscripten)\)`. The instructions for building it are located in the [updated `README.md`](https://github.com/solvespace/solvespace/blob/emscripten/README.md) in this branch.

If you implement a missing feature (please do!) you can send it as a PR against this branch.

## Note on JavaScript libraries

When I was just starting on this port I was looking at implementing the HTML part of the UI in ways consistent with modern JavaScript development. My conclusion is that these are not compatible with the practices that SolveSpace generally uses and results in avoidable inessential complexity and general bloat. I am specifically opposed to using things like npm, babel, ES5, Web Components, React/Preact/Vue, and so on for this port.

My decision was to build it in standard HTML and JS; the SolveSpace platform UI implementation requires very little code and completely eliminating any build dependencies other than Emscripten provides a lot of robustness as well as simplifies things greatly. Plus, it's not really hard; the DOM manipulation and event handling functions required by the platform UI implementation are pretty consistent among all modern browsers.

### CODE REVIEW

**Comment by zhuowei** [comment]
@whitequark 
> Menu mnemonics are broken, the Alt+... hotkeys don't trigger them. No idea why.

At least on macOS 10.14.4 (both Safari and Firefox), `event.key` seems to give fancy unicode characters when pressing a regular keyboard key with alt held down:
Screen Shot 2019-05-20 at 11 23 49 PM

Maybe you need to use `event.keyCode` or something?

**Comment by whitequark** [comment]
@zhuowei D'oh...
```
diff --git a/src/platform/html/solvespaceui.js b/src/platform/html/solvespaceui.js
index 9419cdc..d974356 100644
--- a/src/platform/html/solvespaceui.js
+++ b/src/platform/html/solvespaceui.js
@@ -40,7 +40,7 @@ function setLabelWithMnemonic(element, labelText) {
             var mnemonic = document.createElement('u');
             mnemonic.innerText = matches[2];
             label.appendChild(mnemonic);
-            addClass(element, 'memonic-' + matches[2].toLowerCase());
+            addClass(element, 'mnemonic-' + matches[2].toLowerCase());
         }
         if(matches[3]) {
             label.appendChild(document.createTextNode(matches[3]));
```

**Comment by whitequark** [comment]
@zhuowei That said, you highlight a separate issue. Does the following work for you?
```patch
diff --git a/src/platform/html/solvespaceui.js b/src/platform/html/solvespaceui.js
index d974356..361cf08 100644
--- a/src/platform/html/solvespaceui.js
+++ b/src/platform/html/solvespaceui.js
@@ -40,7 +40,7 @@ function setLabelWithMnemonic(element, labelText) {
             var mnemonic = document.createElement('u');
             mnemonic.innerText = matches[2];
             label.appendChild(mnemonic);
-            addClass(element, 'mnemonic-' + matches[2].toLowerCase());
+            addClass(element, 'mnemonic-Key' + matches[2].toUpperCase());
         }
         if(matches[3]) {
             label.appendChild(document.createTextNode(matches[3]));
@@ -332,7 +332,7 @@ window.addEventListener('keydown', function(event) {
     if(event.altKey && event.key == 'Alt') {
         addClass(document.body, 'mnemonic');
     } else if(!isModal() && event.altKey && (withMnemonic =
-                document.querySelector('.menubar > .mnemonic-' + event.key))) {
+                document.querySelector('.menubar > .mnemonic-' + event.code))) {
         triggerMenuItem(withMnemonic);
         event.stopPropagation();
     } else {
```

**Comment by zhuowei** [comment]
@whitequark This seems to work: I don't have a build environment setup for Emscripten, but manually editing your demo version's DOM to add the `.mnemonic-KeyF` class, then using browser console to add a new keydown listener with the new code, does trigger the File menu on Alt-F.

**Comment by q3k** [comment]
This crashes somewhat reproducibly on Firefox 66.0.3 (64-bit) while rotating the view around with the middle button:

```

RuntimeError: integer overflow solvespace.wasm:714979:1
    __ZN10SolveSpace14GraphicsWindow5PaintEv https://files.whitequark.org/SolveSpace/solvespace.wasm:714979
    __ZNSt3__228__invoke_void_return_wrapperIvE6__callIJRNS_6__bindIMN10SolveSpace14GraphicsWindowEFvvEJPS5_EEEEEEvDpOT_ https://files.whitequark.org/SolveSpace/solvespace.wasm:1609025
    __ZNSt3__210__function6__funcINS_6__bindIMN10SolveSpace14GraphicsWindowEFvvEJPS4_EEENS_9allocatorIS8_EEFvvEEclEv https://files.whitequark.org/SolveSpace/solvespace.wasm:1608486
    __ZNKSt3__28functionIFvvEEclEv https://files.whitequark.org/SolveSpace/solvespace.wasm:523996
    __ZN10SolveSpace8Platform14WindowImplHtml14RenderCallbackEPv https://files.whitequark.org/SolveSpace/solvespace.wasm:584709
    dynCall_vi https://files.whitequark.org/SolveSpace/solvespace.wasm:6951237
    dynCall_vi https://files.whitequark.org/SolveSpace/solvespace.js:10826
    dynCall https://files.whitequark.org/SolveSpace/solvespace.js:548
    dynCall_wrapper https://files.whitequark.org/SolveSpace/solvespace.js:527
    wrapper https://files.whitequark.org/SolveSpace/solvespace.js:7209
    safeRequestAnimationFrame https://files.whitequark.org/SolveSpace/solvespace.js:6740
```

**Comment by whitequark** [comment]
@q3k Yes, this is a known issue in wasm. I'd need to look at a way to make overflowing float to integer conversions defined without losing performance or compatibility.

**Comment by whitequark** [comment]
I've updated the branch to use upstream (i.e. LLVM's) wasm support in emscripten. This results in a very nice 5.5 MB deployable binary when built with `-O3`.

**Comment by vespakoen** [comment]
Just want to tell you that this is super awesome!! Love seeing things like this being ported to the web =)
Would it be possible to have the solver compiled separately so it can be used in other applications?

**Comment by whitequark** [comment]
The solver is already buildable separately. I think you can just use current code from master with possibly minor modifications if you want to use it in your own WASM application.

**Comment by mmiscool** [comment]
How is this going. I played with the demo but it seems to have a offset on the mouse pointer location.

**Comment by whitequark** [comment]
@mmiscool I haven't spent much time on this PR as other SolveSpace issues seemed more important. Which browser are you using?

In general, this PR probably won't be usable with real world designs until something is done with savefiles, which is a rather large task; right now there is no way to load an assembly in the web version even in principle.

**Comment by mmiscool** [comment]
> @mmiscool I haven't spent much time on this PR as other SolveSpace issues seemed more important. Which browser are you using?

@whitequark I am using google chrome. 
See the following video for behavior. 

https://youtu.be/15hT13KPBMs

> In general, this PR probably won't be usable with real world designs until something is done with savefiles, which is a rather large task; right now there is no way to load an assembly in the web version even in principle.

For file management have you looked at using local storage? The solvespace file format is just text at the moment, I could put together some javascript to handle file management.

**Comment by whitequark** [comment]
> For file management have you looked at using local storage? The solvespace file format is just text at the moment, I could put together some javascript to handle file management.

I'm well aware of local storage. I don't consider a solution that is limited to 5 MB of total model size (which is easily exceeded as SolveSpace serializes triangle mesh to text with high decimal precision) and requires manual synchronization between browser and desktop acceptable.

**Comment by whitequark** [comment]
> See the following video for behavior.

That's a known issue. IIRC Chrome flat out broke the devicePixelRatio API several months back, at some point after I did the port.

**Comment by Evil-Spirit** [comment]
> right now there is no way to load an assembly in the web version even in principle.

Assembly files can be opened one-by-one through openfile dialog. Hard, but then we can save all the assemby into one metafile (zipped folders for ex).

**Comment by whitequark** [comment]
> Assembly files can be opened one-by-one through openfile dialog.

Again, I don't consider that solution acceptable.

> but then we can save all the assemby into one metafile (zipped folders for ex).

This has been the plan for the new file format for a long time, and once this is implemented, then emscripten port can actually be released.

**Comment by mmiscool** [comment]
I would be interested in abstracting the file storage with a bit of javascript. I have another project that uses a database for managing storage of parts from a multi cad environment. 

If file storage was done with an array of objects that could be accessed with the addition of some javascript it would be great.

**Comment by whitequark** [comment]
Is that for Autodrop3d? I understand that it would be convenient for your project, but I don't think it's the right choice for upstream SolveSpace.

That said, I think you'll find it fairly easy to implement file operations in a similar way to other JavaScript implementations of platform APIs, and if not, I will gladly assist you with that.

**Comment by mmiscool** [comment]
@whitequark 
I will work on getting some javascript put together for talking to my back end and try to ensure that it is generic so that other can use it a a basis for other similar server integration.

**Comment by whitequark** [comment]
Cool! I'll see how much of that could be integrated.

**Comment by whitequark** [comment]
I've rebased the branch on master and fixed a few minor issues.

**Comment by zopieux** [comment]
If anyone's interested in this Emscripten port, [I've rebased this commit](https://github.com/zopieux/solvespace/commit/a90e9951911ea20d36f286c3fb4b8f34bdccf37f) against current master and fixed a few errors caused by emscripten breaking changes, such as the DOM library now using `querySelector` instead of `getElementById`. It builds and runs fine using Arch packages as of today.

**Comment by ruevs** [comment]
@whitequark I think you will be glad to hear that after @verylowfreq picked up the Web emscripten port in https://github.com/solvespace/solvespace/pull/1275, it is now merged in trunk here 7415048a5769c78fc4bb02afa426d101059374d . 

He also has saving and opening of files and gestures (for touch screens/phones/tablets) working here:
   https://github.com/verylowfreq/solvespace/commits/feature-em-fileio
   https://github.com/verylowfreq/solvespace/tree/emscripten-develop
And a live version with these changes here:
  https://verylowfreq.github.io/experimental-solvespace-on-browser/

With this I am closing this pull request. Thank you for all the great work - I can not say this enough times :-)

**Comment by ruevs** [comment]
More improvements in #1308

**Pull request closed without merging**
