### PR TITLE
More cleanups and simplification

### PR DESCRIPTION
**Pull request by rpavlik**
This mostly cleans up the remaining pieces I had in flight, plus some extra cleanups. tests pass, the containers aren't very different (still allocated the same), but this lets the "port" to backing by std::vector be fairly simple in addition to making things cleaner and more uniform.

### CODE REVIEW

**Comment by rpavlik** [comment]
Apparently the windows toolchain is too old to deal with defaulting move constructors, etc. Fortunately, this is apparently not necessary anymore, so I just dropped those patches from the series.

**Comment by rpavlik** [comment]
Ah ha! I took a different approach to doing the IdListAdditions thing and added a MergeInto method. This let me get rid of nearly all remaining non-range-for over IdLists. See last two commits in https://github.com/rpavlik/solvespace/commits/idlist-merge

**Comment by whitequark** [comment]
That's definitely one way to do it, yup.

**Comment by rpavlik** [comment]
OK, this has been rebased and squashed into fewer commits with better messages. I've also included the MergeInto work on IdList, and tweaked the "get rid of qsort" commit to use lambdas for simplicity.

This removes nearly all non-range-for loops over containers, at least those that I had detected when I first marked them with comments a year ago. It also addresses the underlying reasons why some couldn't be ported to range-for, such as addition-during-iteration. The other changes are rather standalone - think you can mostly drop any ones you don't care for in the series.

The underlying motivation behind these changes is either performance (for those that originated long ago), or improved software structure (for newer ones) - many of these issues were noticed when I attempted to port these containers to being based on std::vector or something else, but the fixes didn't depend on such a port.

**Comment by rpavlik** [comment]
OK, undoing the merge-idlists commit because it apparently is resulting in benchmark issues locally?

**Comment by whitequark** [comment]
Thanks for the update! I didn't forget about this PR, was just a bit busy with other projects.

**Comment by rpavlik** [comment]
np - I just poked at this again to verify a vscode bug had been fixed, and one thing led to another ;)

**Comment by whitequark** [comment]
@rpavlik I just reviewed all these changes. I am quite happy with how they are. Could you do a rebase and then I'll merge it?

**Comment by rpavlik** [comment]
oh this is a fun rebase - forgot that I did the "remove all the `.v`" on a separate branch :) Almost done.

**Comment by whitequark** [comment]
(This is still a *lot* of churn, but it is churn I was prepared to apply anyway, and I am convinced that SolveSpace urgently needs to be modernized if we are to seek healthy external contributors. The current situation where anyone has to learn the unconventional data structures first to do anything is not really sustainable...)

**Comment by rpavlik** [comment]
OK, rebase complete! Thanks for the review!

**Comment by whitequark** [comment]
You've made some excellent contributions to SolveSpace, and as such I've invited you to the SolveSpace organization. For now I would still like all non-trivial changes go through pre-commit code review, but feel free to commit trivial ones directly (typos, broken build, etc.)

**Comment by rpavlik** [comment]
Thanks, and thanks for your excellent and prompt reviewing - if only I was as prompt on my PR reviews :)

**Pull request merged**
