### PR TITLE
README: Add Travis & Snap Store badges

### PR DESCRIPTION
**Pull request by ppd**
Do we want something like this? I'm proposing it to start a discussion. 

Maybe something like a licence badge too:

GitHub

### CODE REVIEW

**Comment by phkahler** [comment]
I like badges, but where should they appear? It also seems like we should have the SolveSpace icon on the github page.

**Comment by ppd** [comment]
Most projects place the badges just below the title (like proposed in this PR) or in a table somewhere below. I like the former better.

Regarding the icon: like below, but vertically centred?

#  SolveSpace

**Comment by ruevs** [comment]
The license badge is superfluous - the license is obviously indicated on the main page.
What does the third link do?
https://snapcraft.io/solvespace/trending.svg?name=0

**Comment by ppd** [comment]
If we went trending in the store (don't know what that actually entails), this would display another badge:

Screenshot from 2020-10-28 19-16-15

**Comment by ruevs** [comment]
Fine with me. Makes it look more "modern" (whatever that means ;-)

**Comment by ppd** [comment]
Aligning the icon like this requires the use of the depreciated `align` attribute. But tons of projects on GitHub don't care.

We could also push it to the right side; there's tons of space.
Or maybe like a banner: https://github.com/anfederico/Clairvoyant#readme ?

**Comment by phkahler** [comment]
I had also wondered about a banner and made a doodle ;-)
SolveSpace
[SolveSpace.zip](https://github.com/solvespace/solvespace/files/5454417/SolveSpace.zip)

**Comment by phkahler** [comment]
I also like the pair of images over at the snap store - one sketch and one assembly including a part made from the sketch - it's more realistic.

**Comment by ppd** [comment]
@phkahler Those are from http://solvespace.com/examples.pl

We could also kinda copy the snap store landing page:
1. Logo left in heading
2. Badges right in heading
3. Repo description in second row
3. Gallery in third row

**Comment by phkahler** [comment]
> One thing to consider: the more styling and HTML we use, the farther we stray from KISS markdown elegance.

I like simple. Make it so!

**Comment by ruevs** [comment]
@ppd @phkahler is there a reason you did not delete the https://github.com/solvespace/solvespace/tree/readme-badges  branch?

**Comment by ppd** [comment]
> is there a reason you did not delete

Yes: forgetfulness.

**Pull request merged**
