### PR TITLE
Final Update of Changelog for 3.0

### PR DESCRIPTION
**Pull request by ruevs**

### CODE REVIEW

**Comment by Symbian9** [comment]
Also add that UI icons was redesigned.

**Comment by ruevs** [comment]
The icon update is purely cosmetic.

Turntable navigation instead like SketchUp may be a good idea. @phkahler ?

**Comment by rpavlik** [comment]
I'd remove the thing about q3d that entered and left before 3.0. I'd also fix the markdownlint issues. I had a branch in progress for that I didn't push - now it's at https://github.com/ruevs/solvespace/pull/1

**Comment by ruevs** [comment]
Done

**Comment by Symbian9** [comment]
> Done

But mention of *SketchUp* is not replaced!?

**Comment by ruevs** [comment]
@Symbian9 00533a0fb22c85293d253f998c8d6f30029061ea

**Pull request merged**
