### PR TITLE
Handle operators 2

### PR DESCRIPTION
**Pull request by rpavlik**
Alternate to #447 - doesn't have the operator bool stuff, but you at least get ==, !=, and <. Let's see what CI thinks.

### CODE REVIEW

**Comment by whitequark** [comment]
@jwesthues Any strong opinions on this change? It adds a bit of type safety in that it's an error to compare unrelated handles, and it makes maps with handles as keys a bit nicer. And although I'm very much not fond of the way C++ manages to provide basic functionality, this implementation is not invasive and shouldn't cause us any problems like doing this with CRTP.

**Comment by jwesthues** [comment]
Seems reasonable to me.

**Comment by whitequark** [comment]
Thanks @rpavlik!

**Comment by phkahler** [comment]
Yes, thanks @rpavlik. I like the readability improvements this brings.

**Pull request merged**
