### PR TITLE
Python wrapper of the solver

### PR DESCRIPTION
**Pull request by KmolYuan**
#292 The first pull request of Python wrapper branch.

New folder:
+ `cython`

Modified files:
+ ` .gitignore`: Ignore the project settings of JetBrains IDE.
+ `.travis.yml` and `appveyor.yml`: Deployment of PyPI.
+ `src/platform/platform.cpp`: Add a type cast for MinGW and newer version compiler.

### CODE REVIEW

**Comment by ruevs** [comment]
@vespakoen are you aware of this?
https://github.com/solvespace/solvespace/pull/419
https://files.whitequark.org/SolveSpace/solvespace.html

**Comment by vespakoen** [comment]
Yes I have seen the webassembly version, but I would like to package up the **core only** as a Node.js / browser package.

**Comment by blooop** [comment]
I'd just like to say that I am very interested in python bindings for an up to date version of solvespace, so this pr looks great.  

Thanks

**Comment by vespakoen** [comment]
I think providing SolveSpace's solver as a library would be great for many other projects, and also hopefully would get more people working / improving on it.

It would be great if the SolveSpace CI can produce these libraries automatically for every platform.

The most "universal" way I think is by using pybind (For Python), embind (For the web) and n-api (For node.js), they are all very similar, and work the best by wrapping a class.

Also, by moving as much logic as we can into a C++ class, the bindings can be smaller, and there is less "wrapper code" that we would have to maintain.

I would happily take on the job of hooking it into our CI to have it produce the libraries for all the platforms, I just don't know what this class should look like exactly.

Anyways, this is definitely something I want to take a look at in the near future.

**Comment by blooop** [comment]
That sounds great.  I agree about pybind11 for python bindings,iI found its very easy to generate bindings with minimal extra code/maintenance. 

I have been looking into cadquery for code based CAD, but am still struggling to work out the right code to do things.  
I read this paper:
https://onlinelibrary.wiley.com/doi/full/10.1111/cgf.14046

which basically says, gui cad is quick and easy to use, but not as robust as code, but code is difficult to understand.  They come up with a dual system which allows gui creation but also saves a code representation so gets the best of both worlds.  

I was thinking of trying to do something similar with solvespace but I'm guessing it will be a lot of work.

**Comment by vespakoen** [comment]
CadQuery is a very cool project indeed, there is also OpenSCAD (and OpenJSCAD) which might be of interest to you.

And I guess we should not forget "SWIG" for generating external bindings to SolveSpace, maybe it's even the least invasive but I have no experience using it yet.

**Comment by blooop** [comment]
I started out with openSCAD, but it doesn't have operations like fillet or shell and the language itself is not as nice a python.  

Cadquery fixes those problems but doesn't have constraints so is still rather procedural.  Freecad in theory has everything, but when I started implementing basic programmatic 2D sketching constraints everything was very slow and crashed all the time.

  
And now we come to solvespace, which appears to have everything.  I'm still very early in the research stage so I need to investigate the solvespace code more, but I've been using the editor as my CAD of choice for a while now and have been impressed so far. 

In terms of SWIG, I have not used it, but did not like the look of it compared to pybind11 which I've been using on a large project quite happily for over a year now.

**Comment by phkahler** [comment]
@vespakoen  The reason this is still not merged is I'm not sure what to make of it, and not planning to use it soon. Not even sure what the use cases are yet - to bring the solver to python programs, or to bring python to solvespace? It obviously useful to someone! If you want to take it on we can merge it - probably after 3.0.

It would also be good to squash most of the commits. Down to 5ish?

**Comment by blooop** [comment]
In terms of the use case of bringing the solver to python, it would be useful because then I could add constraints to Cadquery relatively easily which removes one of its biggest weaknesses.

**Comment by ruevs** [comment]
> we can merge it - probably after 3.0.
> 
> It would also be good to squash most of the commits. Down to 5ish?

Does a python whapper of the solver belong in the same repository as the application?

**Comment by robnee** [comment]
> Does a python whapper of the solver belong in the same repository as the application?

The python module seems to depend on mostly the same src/ files as libslvs.  Could the python module depend on libslvs instead?

**Comment by vespakoen** [comment]
Hello Yuan Chang, thanks a lot for this work!

I'd really like to merge this into SolveSpace, so we can have a "officially supported" SolveSpace PyPi package.

It would have been nice if this used the project's CMake, but since it is currently very hard to build the "solver only" with CMake, I can totally see why that has been avoided.
This might be something we can improve in the future, but for now, your setup.py seems to work very well.

One suggestion I have is to use "cibuildwheel" to compile the packages.
This uses the manylinux docker images that have an old glibc version, to ensure compatibility with older linux versions.
I have added it in a fork, and it seems to work pretty well, see: https://github.com/vespakoen/solvespace/tree/python

@jwesthues Can you create an account on PyPi (https://pypi.org/account/register/) and on Test PyPi (https://test.pypi.org/account/register/) and add the API keys to the CI secrets? (as `PYPI_API_TOKEN` and `TEST_PYPI_API_TOKEN`)

@ruevs @phkahler are you ok to merge this?

**Comment by jwesthues** [comment]
Very cool, thanks. I'll await @phkahler's thoughts on merging, and create those accounts assuming it all makes sense to him.

**Comment by phkahler** [comment]
@vespakoen  @jwesthues   I've let it sit because I don't want the maintenance burden. If someone else is willing to deal with this I'm fine with merging it - assuming it makes sense. I've looked into the details of this exactly zero minutes ;-)

**Comment by vespakoen** [comment]
To me this looks like the most up-to-date, minimal implementation for a python wrapper of the solver.

It is also a part of SolveSpace that is very loved, and I think it would be good to have it in the official repository.

I am also fine spending some time on it to make sure it works and keeps working in the future.

**Comment by phkahler** [comment]
@vespakoen  rebase and merge it and you have the job ;-)

**Comment by vespakoen** [comment]
Thanks a lot for this contribution!
A variant of this got merged to master, so I believe this can now be closed

**Pull request closed without merging**
