### PR TITLE
Add a link to the GitHub commit at the bottom of the config screen

### LINKED ISSUE #1172: Feature request: Add build date to the Help->About dialog
Sometimes, it would be nice to easily find out how old my installed build is.
It would be nice if in addition to the revision number, the Help>About dialog contained a date of either the last commit or the build.

### PR DESCRIPTION
**Pull request by ruevs**
The "Go to GitHub commit for 3.0~a88f5d8b" link at the bottom of the configuration screen opens the URL [`https://github.com/solvespace/solvespace/commits/a88f5d8b`](https://github.com/solvespace/solvespace/commits/a88f5d8b) and allows the user to see the date of the commit that SolveSpace was built from.

image

Also revert f1e47e655 https://github.com/solvespace/solvespace/pull/1185

Closes #1172

### CODE REVIEW

**Comment by ppd** [comment]
Oh, very nice, very pragmatic. I wonder if a new menu item in "Help" could also do the trick (there aren't too many); that'd be more discoverable.

**Comment by ruevs** [comment]
Lazy people come up with "pragmatic" solutions :-)
A menu item is just as easy. I'll make an alternative PR for it.

**Comment by ruevs** [comment]
@ppd here is the Help menu variant https://github.com/solvespace/solvespace/pull/1190

**Comment by phkahler** [comment]
Used the other one that puts it in the help menu

**Pull request closed without merging**
