### PR TITLE
Allow comment constraint associated with point entity (WIP)

### LINKED ISSUE #1032: The comments can't move with the shapes
I have made a 2D geometry sketch, and used the comments to mark the point name. When I moved the shapes by selecting and dragging them, the comments around the points didn't move at the same time. When I use the mouse to drag a box to select the whole shape, only the shape itself is selected, and the comment is not selected. And even I click the comments one by one and then selecting the whole shape, the shape and the comments still moved seperately.

I think if I could contrain the shape and the comments as one "group", or constrain the comments lock on the related points, this problem maybe be solved. I hope you can provide this feature.

Attached is the 2D geometric representation that I have drawn. I am trying to provide some basic parameter computing power in SolveSpace by means of plane geometry.
image

### PR DESCRIPTION
**Pull request by robnee**
Allows comment constraints to be associated with a reference point (in addition to the standard "free" mode) so that their position offset is relative to that point.  Moving or removing the reference point affects associated comments.

Things tested:
- does not impact "free" (created with no point selected) constraint behavior in 2D or 3D.
- if created with a selection checks if selection is a single point.
- saves and restores reference point `ptA` in .slvs file
- behavior degrades gracefully when .slvs files with associated comments are opened in version 3.0 and earlier, comment is just rendered offset relative to the workplane origin rather than the reference point.
- deleting the reference point deletes associated comment constraints as it would with any other constraint
- supports multiple comment constraints for a single point.
- rendering in 3D appears to be correct.
- property browser appears to work correctly

Note: this will require 1 new string to be localized.  The wording of the new string could probably be improved.  Perhaps the default comment when there is a reference point could be improved.

This closes #1032

### CODE REVIEW

**Review by ruevs — APPROVED** [review]
This looks good and works as expected. @phkahler what do you think?

I removed the extra empty lie at the end of drawconstraint.cpp and force pushed.

Also added a commit updating all translations.

**Comment by ruevs** [comment]
@robnee @phkahler Thinking some more about this I came up with a slightly different behaviour:

- If a single point is selected associate a newly created comment with it.
- If nothing or more than a point is selected - create a floating comment as before.

This avoids the new error message and keeps the behaviour as it was in all cases but the "one point selected".

What do you think?

I created a pull request https://github.com/solvespace/solvespace/pull/1035.

**Comment by robnee** [comment]
@ruevs I could go with either one.  I like that #1035 is simpler and I find the error dialogs annoying at times :)  I originally thought that new users would find the message helpful in learning about the feature.  I like the term "floating" comment too.

Separately, I'm working on an enhancement to make the property browser displays more informative in places where they are a little thin, like when 3 or more entities are selected etc.  That's almost ready and I was thinking to include an improvement to the comment display with that to mention the reference point and the offset.  Given that, I think I like your approach better.

**Comment by phkahler** [comment]
@robnee  The only thing I don't like in your description is the new text string. Is there a new dialog box? If so, why?  If it's more text in an existing dialog then I'm fine with that kind of update. I also like @ruevs comment above and reference to #1035 which I also need to try.

BTW since you're both in this area of the code, any chance to address #880  IMHO that's a good one for placing dimensions in 3D.

**Comment by robnee** [comment]
> > Separately, I'm working on an enhancement to make the property browser displays more informative in places where they are a little thin, like when 3 or more entities are selected etc.
> 
> While you're in there, see #165 :-) and probably some related issues.

Yes, I'm hoping to address this.

**Comment by phkahler** [comment]
@robnee  I'm going to go with @ruevs version of this. I'm not a fan of adding dialogs in there. Keep the good ideas and commits coming though!

**Comment by ruevs** [comment]
@robnee gets all the credit for this :-) I only got rid of the message :-)

**Pull request closed without merging**
