### PR TITLE
Build simplify

### PR DESCRIPTION
**Pull request by rpavlik**
Builds on #1154 

Some cleanups of the cmake files so they're easier to understand and edit. Also fixes a bunch of CMake warnings.

### CODE REVIEW

**Comment by ruevs** [comment]
Yes, because @phkahler already merged https://github.com/solvespace/solvespace/pull/1154 and you included those two commits in here as well.

By the way your Eigen branch also has them.

**Comment by rpavlik** [comment]
wait, how did the merge happen that I got conflicts from child commits? Did the commits get squashed or something that changed the ID?

**Comment by rpavlik** [comment]
ok well fixed that.

**Comment by ruevs** [comment]
> wait, how did the merge happen that I got conflicts from child commits? Did the commits get squashed or something that changed the ID?

I don't know but the commit IDs "always" end up different on the master branch after merging. I thought it was normal?

**Comment by rpavlik** [comment]
Only if rebased or squashed. If it's a straight "merge" then the commit ID should exist in the history. Anyway, this is ready to review.

**Review by phkahler — COMMENTED** [review]
Build system stuff of such complexity I like to defer to those who have done the majority of the work on that ;-)

**Comment by rpavlik** [comment]
Who has done most of it? I think this is one of the few projects that I contribute to that I haven't been the main person behind the build system maintenance... Usually that's how I get hooked. (That's why MeshLab has CMake instead of qmake now and can use system installed dependencies, etc)

**Comment by ruevs** [comment]
> Who has done most of it?

Whitequark. All the way back to 2015 when she added it https://github.com/solvespace/solvespace/commit/5db5f1e152fb3d01d2e24b122b1d2f0832ac65b2#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a until she left.

Since I don't know anything about CMake - beyond the little I learned to build SolveSpace I can't help you with this.

**Comment by phkahler** [comment]
> Who has done most of it? I think this is one of the few projects that I contribute to that I haven't been the main person behind the build system maintenance...

Well since whitequark departed I'd say it's been @ppd followed by @vespakoen. I figured people knew that since someone requested their review on this one?   ;-)

**Comment by rpavlik** [comment]
Oh I just clicked the suggested people from GitHub 😁

**Comment by rpavlik** [comment]
Rebased for cleanliness.

**Comment by phkahler** [comment]
@rpavlik   Going to close this since the commits were merged as part of the PR that built on this one. You can reopen if that's not quite right.

**Comment by rpavlik** [comment]
Cool thanks!

**Pull request closed without merging**
