### PR TITLE
Flatpak

### PR DESCRIPTION
**Pull request by rpavlik**
I was wondering why we didn't have a flatpak, just a snap, then I noticed we actually did have some flatpak-related stuff. It just needed some updating.

### CODE REVIEW

**Review by ppd — COMMENTED** [review]
Everything seems to be working; very nice. :+1: 

Just one thing that sticks out: 
```
GNOME 3.30 runtime is no longer supported as of 27th January 2020. Please ask your application developer to migrate to a supported platform
```
So we should also use a more recent runtime & sdk for the flatpak while we're (you) at it.

**Comment by ruevs** [comment]
Just cross-linking things ;-)
https://github.com/solvespace/solvespace/issues/336
https://github.com/solvespace/solvespace/issues/347
https://github.com/solvespace/solvespace/issues/344#issuecomment-408624727

**Comment by rpavlik** [comment]
Oh interesting I didn't see that eol notice. Yeah I'll see if I can update stuff a bit.

**Comment by rpavlik** [comment]
There, updated as much as was reasonable and relatively easy.

**Pull request merged**
