### PR TITLE
Add Spanish / Argentina translation

### PR DESCRIPTION
**Pull request by andesfreedesign**

### CODE REVIEW

**Comment by Symbian9** [comment]
¡Gracias! ;)

JFTR, @andesfreedesign, do not sign CLA - it is not needed for contributing!

**Comment by andesfreedesign** [comment]
CLA signed!

**Comment by Symbian9** [comment]
> CLA signed!

@andesfreedesign, no, you should not sign. (see: #1098)

**Comment by andesfreedesign** [comment]
@Symbian9 
Ouch ... I didn't read your comment
How do I cancel the signature?

**Comment by ruevs** [comment]
> @Symbian9
> Ouch ... I didn't read your comment
> How do I cancel the signature?

Doesn't matter. It's not at all critical or important.

**Comment by andesfreedesign** [comment]
@ruevs 
Ok...
I am a teacher in technical schools.
Currently in the early years I am teaching FreeCAD, but my intention is to start teaching Solvespace

**Comment by phkahler** [comment]
> I am a teacher in technical schools.
> Currently in the early years I am teaching FreeCAD, but my intention is to start teaching Solvespace

@andesfreedesign Don't worry. The CLA used to provide the ability to relicense Solvespace under different terms. The ability to do that has probably been lost, are we're accepting contributions without CLA. As a result, solvespace will have to remain GPLv3 licensed forever. By doing the CLA you reduce the complexity of getting that relicensing ability back, but nobody is planning to do that and we really need to figure out how to get the CLA assistant to shut up ;-)

Also very cool that you are teaching with Free Software!

**Comment by phkahler** [comment]
Looks like we need to update one more file. I can get it later:
https://github.com/solvespace/solvespace/blob/master/res/locales.txt

**Comment by Symbian9** [comment]
@andesfreedesign, what is correct name of *"Argentine Spanish"* in Argentine Spanish: ***"Español rioplatense"***?

- https://en.wikipedia.org/wiki/Argentine_Spanish
  - redirects to: https://en.wikipedia.org/wiki/Rioplatense_Spanish

**Comment by andesfreedesign** [comment]
@Symbian9 
The correct name is Castilian ... and it differs from the Castilian spoken in Spain
Also in Spain there are other languages with Basque or Catalan, so it is wrong to say Spanish-Spain

**Comment by ruevs** [comment]
The ISO standard (http://www.lingoes.net/en/translator/langcode.htm) seems to have Spanish (Spain):

es-AR | Spanish (Argentina)
-- | --
es-BO | Spanish (Bolivia)
es-CL | Spanish (Chile)
es-CO | Spanish (Colombia)
es-CR | Spanish (Costa Rica)
es-DO | Spanish (Dominican Republic)
es-EC | Spanish (Ecuador)
es-ES | Spanish (Castilian)
es-ES | Spanish (Spain)
es-GT | Spanish (Guatemala)
es-HN | Spanish (Honduras)
es-MX | Spanish (Mexico)
es-NI | Spanish (Nicaragua)
es-PA | Spanish (Panama)
es-PE | Spanish (Peru)
es-PR | Spanish (Puerto Rico)
es-PY | Spanish (Paraguay)
es-SV | Spanish (El Salvador)
es-UY | Spanish (Uruguay)
es-VE | Spanish (Venezuela)

But I can not find a similar table (if it exists) of how the different Spanish varieties should be called in Spanish.

**Comment by ruevs** [comment]
https://www.localeplanet.com/icu/iso639.html

**Pull request merged**
