### PR TITLE
Fix a crash when opening an empty file.

### PR DESCRIPTION
**Pull request by ruevs**
Fixes: https://github.com/solvespace/solvespace/issues/918

The problem was that here:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/file.cpp#L480
we cleared all groups. Then we tried to read an empty file and therefore this `while` exited immediately:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/file.cpp#L487
and we came to here:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/file.cpp#L548
where there was no `fileLoadError` and thus we were left with no groups, and so this assert failed:
https://github.com/solvespace/solvespace/blob/11a8a0abd5e21a0da6c818674f8b4b657a401a6c/src/graphicswin.cpp#L394
since is is not allowed to have no groups :-)

### CODE REVIEW

**Comment by phkahler** [comment]
I'd prefer "The file is empty."  But it's OK either way.

**Review by phkahler — APPROVED** [review]

**Comment by ruevs** [comment]
You mean remove "it may be corrupt"?
My logic was that a normal user should normally  not have a zero length slvs file, so for them " the file is empty" may be an unpleasant surprise. Not that telling them it may be corrupt will help :-)

**Comment by rpavlik** [comment]
I'm not sure when this message would actually appear - just when e.g. the user has a complete 0 byte slvs file? As such I have no opinion on the strings wording.

That said, the code itself looks reasonable.

**Review by rpavlik — APPROVED** [review]

**Comment by ruevs** [comment]
> I'm not sure when this message would actually appear - just when e.g. the user has a complete 0 byte slvs file?

Yes, only on a 0 byte file.
 Only then the first `fgets` would return 0 (a null pointer).

"If the end-of-file is encountered while attempting to read a character, the eof indicator is set (feof). If this happens before any characters could be read, the pointer returned is a null pointer (and the contents of str remain unchanged)."

**Pull request merged**
