### PR TITLE
de_DE: missing translations

### PR DESCRIPTION
**Pull request by rurban**

### CODE REVIEW

**Comment by phkahler** [comment]
Is there not a key binding for "Extrudieren"? That one seems important.

**Comment by rurban** [comment]
Yes, I added some more shortcuts

**Comment by phkahler** [comment]
Thank you for this update!

**Comment by phkahler** [comment]
@rurban  I'm new to translations. How do we update the .pot file with strings that are currently missing? The en_US translation is missing several strings so I was going to update that but don't they need to be in the .pot file first? Is there an automated way to update the .pot?

**Comment by rurban** [comment]
The normal autotools way is to do `make -C po update-po`
Haven't checked that yet though. All the line numbers are off eg.
There is an automated way, yes. Bis xgettext and msgmerge, I think. But it's about 30 years since I last did that extensively.

**Pull request merged**
