### PR TITLE
Remove GL framebuffer on macOS

### PR DESCRIPTION
**Pull request by vespakoen**
This is work done by @troughton (see: troughton@42f187a).

See his comment in this issue: #354
I just wanted to turn it into a PR on this repository so more people can see it, and possibly try it out / continue working on it.

I can compile and run this, it make SolveSpace very fast again!
However, there is some flashing in the toolbar occurring now and then, and there are probably other issues that I haven't stumbled into yet.

Notice that this PR does not bring in the changes that @troughton made to src/render/gl3shader.cpp.
Those seemed to be another optimisation that I don't fully understand, and we might be able to do without.

Can someone tell me how to crash it / what needs to be done to get this working reliably?

This PR is supersedes #502

### CODE REVIEW

**Comment by vespakoen** [comment]
From the other PR:
> If you add a constraint, and double click on the text, can you edit it? Or does it disappear / become black eventually? What about scrollbars and tooltips? That's the reason it uses offscreen rendering right now.

@whitequark I don't see any of this above issues, the only thing I see that is strange is that the toolbar sometimes disappears for a frame or 2.

**Comment by whitequark** [comment]
> I don't see any of this above issues

Great! I assume they finally fixed whatever issue there was with GL layers. I'm going to recheck if this still works on Mavericks, I think.

Feel free to remove all traces of `GlOffscreen`, since it was only used for Gtk 2 and macOS and we have long migrated off Gtk 2.

**Comment by whitequark** [comment]
> the only thing I see that is strange is that the toolbar sometimes disappears for a frame or 2.

Is it just the toolbar? Or does selection marquee and fps counter also blink?

**Comment by whitequark** [comment]
I think your patch at least breaks non-HiDPI screens.

**Comment by whitequark** [comment]
That was caused by a missing
```
self.wantsBestResolutionOpenGLSurface = YES;
```

**Comment by vespakoen** [comment]
Cool! Shall I add it to this PR or will you do it along with the other changes you made?

**Comment by whitequark** [comment]
I'll do it.

**Comment by vespakoen** [comment]
Great, thanks a lot! it's great to have a butter smooth SolveSpace again =)

**Comment by whitequark** [comment]
Fixed in 9b61f988. Let me know if there are any issues.

**Comment by vespakoen** [comment]
Working great on my end! Thanks a lot!

**Comment by vespakoen** [comment]
Here is a macOS build from the latest master 54015b6777d2195d54f1738d80c5aa20f194a6b8 
I signed and notarised it using my Apple Developer account for anyone interested to check it out.

[solvespace.zip](https://github.com/solvespace/solvespace/files/3882638/solvespace.zip)

**Pull request closed without merging**
