### PR TITLE
Rebased @verylowfreq Emscripten Fixes

### PR DESCRIPTION
**Pull request by vespakoen**
I rebased @verylowfreq's changes from #1275 to the latest master branch over here, will review this later today.

### CODE REVIEW

**Comment by verylowfreq** [comment]
@vespakoen Thanks :smile:
I checked this and this is same that I thought to do. This can be built successfully and runs. And thank you for reviewing.

**Comment by ruevs** [comment]
@verylowfreq I think it is better to keep most of the history of your changes when merging in master - it has some interesting details.

**Comment by verylowfreq** [comment]
@ruevs I agree. That would be better.

**Comment by ruevs** [comment]
Equivalent changes merged in master here f7415048a5769c78fc4bb02afa426d101059374d .

**Pull request closed without merging**
