### PR TITLE
Use recent flatbuffers commit to solve compiling issue on OpenBSD

### PR DESCRIPTION
**Pull request by lenzj**
Update extlib/flatbuffers to commit google/flatbuffers@de1f034 to solve #745

### CODE REVIEW

**Comment by ruevs** [comment]
This is nice. Only one question - when we update our flatbuffers submodule to to this commit on their master - how much do we have to test? 411 modified files... Is their master "stable" for our needs? How do we find out?

**Comment by lenzj** [comment]
Yes, very good point.  I was wondering that myself but wasn't sure of the best way to do this.  The actual update to flatbuffers to fix OpenBSD compile is very simple (only a couple lines of additional ifdef preprocessor code), but since the commit is recent it pulls in a bunch of other commits that are unrelated to this fix.  The other option would be to patch the existing code with this fix to avoid pulling in the other 411 modified files.

I did a compile and quick functional test on OpenBSD with Solvespace opening, modifying, and saving a few files, but fully admit it wasn't a comprehensive test.

Let me know if there's anything I can test or evaluate to help ensure this is stable.

**Comment by ruevs** [comment]
Looking into it even more, it seems to me that SolveSpace is the only program (in this universe) that exports Q3D files and since the pull request in Horizon EDA https://github.com/horizon-eda/horizon/pull/236 was not merged - nothing imports them. So this change is extremely low risk ;-)

**Comment by phkahler** [comment]
I'm thinking we don't care about Q3D but it probably won't be broken. The main reason for flat butters IIRC was to help reading and writing the new solvespace file format that was going to be needed for a bunch of improvements that never got implemented. I wasn't sure if any of it got used for existing file I/O or not, but it sounds like not?

**Comment by phkahler** [comment]
Why is there no report from Travis here? I expect it to pass, but there is no indication either way.

**Comment by lenzj** [comment]
I thought when I create a pull request or push a new commit that it automatically triggers the CI tests?  Let me know if there's something I should do to start Travis.

**Comment by phkahler** [comment]
@lenzj  nothing wrong on your end. @ppd or @vespakoen  any comment on why Travis either didnt trigger on the PR or just isnt reporting a result?

**Comment by ruevs** [comment]
> Why is there no report from Travis here? I expect it to pass, but there is no indication either way.

I was wondering that myself. I don't know, but perhaps Travis does not detect or does not react on changed submodule versions?

**Comment by ppd** [comment]
That seems like a Travis glitch, or maybe a GitHub Travis app glitch where it didn't even call the Travis A PI. I see no reason why it should be any different for "just" a changed submodule; it's a proper commit. Let's try closing & re-opening this PR. That should trigger a build again.

**Comment by ruevs** [comment]
Travis is there - on a new "Checks" tab at the top :-D

**Comment by ppd** [comment]
> Travis is there - on a new "Checks" tab at the top :-D

Yes. That was triggered by closing & re-opening this PR. Or do you mean you did not have the "Checks" tab at all before?

**Comment by ruevs** [comment]
> Yes. That was triggered by closing & re-opening this PR. Or do you mean you did not have the "Checks" tab at all before?

Probably I did not notice it :-)  It used to show up inline with the comments last time I paid attention.

**Comment by phkahler** [comment]
> > Travis is there - on a new "Checks" tab at the top :-D
> 
> Yes. That was triggered by closing & re-opening this PR. Or do you mean you did not have the "Checks" tab at all before?

Is that tab new? I never noticed it. I always look for the big green Circle with "All checks have passed" after the comments by "Rebase and Merge". It wasn't there earlier on this PR but it is now. BTW it's very pleasing that it works now. I used to have to verify that it was just macOS that failed to know it basically passed ;-)

**Comment by ppd** [comment]
I think that tab's been there since GitHub started pushing their own CI "GitHub Actions". However, I remember enabling some kind of beta UI features a while ago. Maybe it has just been rolled out in their stable UI.

**Pull request merged**
