### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by ktrace**
Remove duplicated

### CODE REVIEW

**Comment by rpavlik** [comment]
I hit some issues regarding this in packaging, fixed it a little differently in #1243

**Comment by rpavlik** [comment]
Looks like we do actually need SparseCore in solvespace.h because the insides of System require Eigen::SparseMatrix (and Eigen::VectorXd). However, that include is in fact the minimal include to get those types.

**Comment by phkahler** [comment]
So close this in favor of #1243 then?

**Comment by ktrace** [comment]
> So close this in favor of #1243 then?

Yes, of cause. #1243 solve problem better.

**Pull request closed without merging**
