### PR TITLE
Merge pull request #1 from solvespace/master

### PR DESCRIPTION
**Pull request by DopplerBit**
Sync from master project

### CODE REVIEW

**Comment by phkahler** [comment]
What on earth is this?

**Comment by ruevs** [comment]
Looks like a mistake. @DopplerBit ?
But there is a commit in another branch that is new https://github.com/DopplerBit/solvespace/commit/18524017dc44e286d8b332ad9d97b8197321094f ?

**Comment by ruevs** [comment]
> I think we should wait for a PR though rather than grab it

I agree :-)

**Comment by phkahler** [comment]
@DopplerBit  Closing this pull request as probably a mistake. You can reopen it if that's not the case.

**Pull request closed without merging**
