### PR TITLE
Fix issue659 - Problems constraining to ends of Helix.

### PR DESCRIPTION
**Pull request by phkahler**
Create a new copy type for faces that includes the translation aspect of helical extrusions. Also swap the end remappings when the shell is inside out - this was also affecting some Revolve extrusions.

### CODE REVIEW

**Comment by whitequark** [comment]
Hm, looks like mimalloc causes all of our tests to fail.

**Comment by phkahler** [comment]
> Hm, looks like mimalloc causes all of our tests to fail.

Did you respond to the wrong PR?

**Comment by whitequark** [comment]
Nope, I was looking into why tests fail.

**Comment by whitequark** [comment]
I filed https://github.com/microsoft/mimalloc/issues/279.

**Comment by whitequark** [comment]
Seems like they pushed a fix upstream, do you think you can check if their commit fixes the issue?

**Comment by phkahler** [comment]
> Seems like they pushed a fix upstream, do you think you can check if their commit fixes the issue?

How do I even test that? No sure how to update the link to a newer version of mimalloc (or other external libs) so that Travis will use it.

**Comment by nabijaczleweli** [comment]
`git pull https://github.com/microsoft/mimalloc dev` in `extlibs/mimalloc` will update the submodule, and `git log` there should show the commit with the fix. Then `git diff` of `extlibs/mimalloc` should show the new SHA.

**Comment by phkahler** [comment]
@nabijaczleweli Thanks, but I'm still missing something. First, I can't reproduce the issue here, the  tests pass. It would be cool to issue a PR using a newer mimalloc and let travis test it but I'm not sure how to update the external link itself. Locally I have folders full of code, not links with hashes.

**Comment by nabijaczleweli** [comment]
And those folders full of code are git repositories of their own, with the HEAD showing up if you diff them from the parent project:
image

I pushed the commit to a branch here for demonstration purposes: https://github.com/nabijaczleweli/solvespace/tree/submodules-how-do-they-work

**Comment by phkahler** [comment]
Thanks!  I tried that here and then made a PR to see if it fixes the problem.

**Pull request merged**
