### PR TITLE
Delete es_AR.po

### PR DESCRIPTION
**Pull request by andesfreedesign**
Delete the file as it has many modifications ...
I am going to add the new file corresponding to the updated messages.pot

### CODE REVIEW

**Comment by phkahler** [comment]
The current edge build works fine and has es-AR language support. Pull from master and just update the po file and create a pull request with that change.

**Comment by andesfreedesign** [comment]
@phkahler 
I do not know what will be the error that occurs in the Windows test ...

**Comment by phkahler** [comment]
> The file was left with many commented lines at the end ...

That seems to be normal for .po files. I used to delete them, but then I got the impression that they can be used by some tools for something like hints for automatic translation or suggestions. I really don't know if the commented lines are useful or not.

**Comment by Symbian9** [comment]
> I used to delete them, but then I got the impression that they can be used by some tools for something like hints for automatic translation or suggestions. I really don't know if the commented lines are useful or not.

Comments in PO-files especially useful for translators, especially for collaborative work on translating.

**Comment by andesfreedesign** [comment]
> > I used to delete them, but then I got the impression that they can be used by some tools for something like hints for automatic translation or suggestions. I really don't know if the commented lines are useful or not.
> 
> Comments in PO-files especially useful for translators, especially for collaborative work on translating.

No, precisely the commented lines mentioned by @phkahler  are not useful ...

**Comment by ruevs** [comment]
In fact they are. If the message re-appeares in the future it is automatically translated.

**Comment by ruevs** [comment]
In fact they are. If the message re-appeares in the future it is automatically translated.

**Comment by andesfreedesign** [comment]
> In fact they are. If the message re-appeares in the future it is automatically translated.

What happens is that these messages are incorrect ... and I consider that the Edge version is badly translated.
I have the latest translation done from the updated messages.pot, and on my computer it compiles perfectly ...
I don't know why the error occurs in the Windows test

**Comment by phkahler** [comment]
@andesfreedesign  Can you start from master, make a branch, replace the .po file, and make a new pull request? Everything is fine except the new translation updates. This PR contains a number of redundant commits, as well as unwanted changes to CMake stuff.

Thanks!

**Comment by andesfreedesign** [comment]
> @andesfreedesign Can you start from master, make a branch, replace the .po file, and make a new pull request? Everything is fine except the new translation updates. This PR contains a number of redundant commits, as well as unwanted changes to CMake stuff.
> 
> Thanks!

Ok, I'm going to create a branch and work on the translation from there ...
Thanks!

**Pull request closed without merging**
