### PR TITLE
Delete the partially drawn entity when ESC is pressed on pending oper…

### LINKED ISSUE #1385: Feature Request: Drop last segment in a line when pressing escape
### System information

- **SolveSpace version:**3.1 
- **Operating system:**All 

### Expected behavior
When drawing segments (straight lines), if I haven't set the last segment endpoint that line disappears when I press Escape

### Actual behavior
When drawing segements, I click on where I want each line to end, but if I don't want to close the shape and press Escape to exit Segments the last line that I didn't want is drawn to where ever the mouse pointer was

### PR DESCRIPTION
**Pull request by phkahler**
…ations by using UndoUndo()

Fixes #1385

### CODE REVIEW

**Comment by ruevs** [comment]
Hmm... I'll need to pull compile and trace through this if you want an opinion.

**Comment by phkahler** [comment]
> Hmm... I'll need to pull compile and trace through this if you want an opinion.

Actually no. It works.

**Comment by ruevs** [comment]
> Actually no. It works.

@phkahler actually no, it makes it impossible to draw open bezier splines 😛 😃

**Comment by phkahler** [comment]
> > Actually no. It works.
> 
> @phkahler actually no, it makes it impossible to draw open bezier splines 😛 😃

Right click to end the spline. But I'm definitely open to a version of ESC that stops the spine creation rather than undoing it.

**Comment by ruevs** [comment]
I'm so used to ESC that I completely forgot about right-click :-)

**Comment by ruevs** [comment]
Made a pull request https://github.com/solvespace/solvespace/pull/1497

**Pull request merged**
