### PR TITLE
fix: use macOS Frameworks

### PR DESCRIPTION
**Pull request by dgramop**
We want solvespace to dynamically link with only one OpenGL library at a time, in particular the one that ships with MacOS. For this we use macOS frameworks, and pass the appropriate flag to the linker.

We should not use default cmake logic for finding openGL, since it seems to find the wrong version of libGL, that may have been installed by some other package at some point.

Closes issue #1454

### CODE REVIEW

**Comment by dgramop** [comment]
We can close that issue regardless of whether this PR is accepted :)

I think I figured out what's broken and it's unclear if Solvespace should change, find_package in cmake should change, or if whatever package in homebrew or elsewhere that provides /opt/local/lib/libGL.dylib should change.

The case for this PR and making the change in solvespace or CMake's FindOpenGL module is that it makes solvespace more resilient to other weird non-system installs of openGL in MacOS

**Comment by ruevs** [comment]
It's interesting why did CMake [find the "wrong" OpenGL on your system](https://github.com/solvespace/solvespace/issues/1454#issuecomment-2036348552).
According to the [documentation](https://cmake.org/cmake/help/latest/module/FindOpenGL.html#macos-specific) it should have used the framework. Perhaps (as you mentioned) it is a problem with CMake, or is it the way we are using it? My experience with CMake is very limited - @rpavlik and @vespakoen - do you have some time to lreview this?

@dgramop does the new artefact (built by the CI in this pull request) work for you? (I hope you can see it).

**Comment by dgramop** [comment]
I agree with the scare quotes around "wrong", I wonder if some other software that uses cmake relies on its behavior on macOS to find whatever it found on my system instead of just using the framework. 

I can't see the MacOS artifact for the PR. I can see artifacts for commits pushed to master, this one just has "solvespace-x86_64".

**Comment by ruevs** [comment]
> I can't see the MacOS artifact for the PR.

Sorry I forgot - the CI for pull requests does not keep the artefacts.

**Comment by dgramop** [comment]
Hey! Just checking in, did anyone get a chance to try this out on a mac? Maybe there was something I mistinterpreted and was supposed to follow up on?

**Comment by dgramop** [comment]
🎵🎵
"can any-body find meeeeeeeeee"
"somebody toooooooooo"
"~~looooove~~ review my pull request"
🎵🎵

~ in the off chance that somebody with a mac has time to review this, I'd really appreciate it :)

**Comment by ruevs** [comment]
> "can any-body find meeeeeeeeee"
> "somebody toooooooooo"
> "~looooove~ review my pull request"

With such a nice request I'll have to dig out my machine that has a macOS VM on it... it'll  be "deep" digging... hopefully someone on a real Mac takes a look in the meantime :-D

**Comment by phkahler** [comment]
What does it take to set up a build environment on osX? I've got a 2013 MBA but it doesn't have Xcode on it and I don't think the app store is working well on it, and it's got a fairly old OS. It runs Solvespace but I don't build on it.

**Comment by BKLronin** [comment]
Fyi: There is this easy to setup proxmox osx script. I'm using this for the intel builds on an N100. (Runner and gui tests)

https://github.com/luchina-gabriel/OSX-PROXMOX

**Comment by ruevs** [comment]
> What does it take to set up a build environment on osX?

On my macOS 10.14.6 (18G9323) Mojave
all I had to do was install Xcode 11.3.1 (the latest supported) and then follow the official instructions.

My make command is:
`cmake .. -G Xcode -DCMAKE_BUILD_TYPE=Release -DENABLE_OPENMP=ON`
and then I just open the resulting `solvespace.xcodeproj` and build it.

**Comment by dgramop** [comment]
I see. Glad the cmake change worked, but I'm not really sure about Xcode. I didn't even try building with Xcode. Does master usually build correctly through Xcode?

**Comment by ruevs** [comment]
> Does master usually build correctly through Xcode?

It does build just fine.

**Comment by dgramop** [comment]
Hmm, I’m not even making it past the CMake step when i try configuring for XCode

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
