### PR TITLE
"Edit newly added dimensions" is now turned on by default. issue826

### PR DESCRIPTION
**Pull request by phkahler**

### CODE REVIEW

**Review by ruevs — CHANGES_REQUESTED** [review]
Change

Enable -> Edit

In the commit message ;-)

**Comment by ruevs** [comment]
I'll merge this. @phkahler please let me know if you want me not to merge even "obvious" things in the future.

**Comment by phkahler** [comment]
@ruevs  Yes please merge stuff like this. The reason I asked you to review is that I just wanted a sanity check before merging/closing since I didn't want to figure out how to reset the config to default. I like to either have someone look at things and/or let the PR sit over night before I merge my own commits - I often decide it's not quite right in that time.

**Comment by ruevs** [comment]
Yes that is why I don't (want to) merge my own pull requests :-)

Before merging I did check this by deleting the registry key `HKEY_CURRENT_USER\Software\SolveSpace\ImmediatelyEditDimension`, running and confirming that new dimensions are edited immediately and the option is on.

**Pull request merged**
