### PR TITLE
Minimal eigen

### PR DESCRIPTION
**Pull request by rpavlik**
Here's just some small Eigen parts from my branch. Does not include the big refactor by @Evil-Spirit , but long ago I did find that these improved performance nonetheless.

Builds on #1155

### CODE REVIEW

**Comment by ruevs** [comment]
@rpavlik https://github.com/solvespace/solvespace/pull/432 did you forget it? ;-)

**Comment by rpavlik** [comment]
yes I sure did.

**Comment by ruevs** [comment]
@rpavlik would you restore this branch please. On the weekend I decided to test it with a bunch of "performance models" but noticed you deleted it. I have an older local copy in one of my GIT clones but it is missing some things.

**Comment by vespakoen** [comment]
You should be able to fetch this PR using its ID (1156).
See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

NOTE: I didn't try it out and it may not work

**Comment by ruevs** [comment]
@vespakoen thanks! I did not know that. It works.

**Pull request closed without merging**
