### PR TITLE
Move z-index of construction segments behind normal segments

### PR DESCRIPTION
**Pull request by vespakoen**
Right now, when drawing a segment on a construction segment, the segment becomes invisible.

I think it makes more sense that construction lines stay in the background.

This change seems to do the trick.

### CODE REVIEW

**Comment by phkahler** [comment]
This scares me because the picking code is so complicated. At the same time I'm happy someone else is having a look at it. I'd like to try a bunch of sketches with this before merging.

There is at least one open issue this might help with - see #173.  I've found that rotating the view slightly and fiddling with the exact mouse location can sometimes allow me to pick a different line, but this will make that impossible. So is it really the best solution?

**Comment by phkahler** [comment]
@vespakoen  The CI is failing with:
test/constraint/angle/test.cpp:69: FAILED: render doesn't match reference; 12 (0.00%) pixels differ

Looks like only one of the test images needs to be updated to match. To quote whitequark on fixing this:
"When you run the tests locally, for failing tests, you get an actual result next to the reference result. Rename the former to the latter, done."  from discussion on #627 talking about test suite images. IIRC the result images might be automatically deleted if the test passes? If that's the case, delete the reference image and rename the result to the reference - after comparing them to be sure nothing is actually broken.

**Comment by phkahler** [comment]
I'm not sure why the image is different. The change affected more than selection.

**Comment by phkahler** [comment]
Oh, it's broken on master I think.

**Comment by phkahler** [comment]
@vespakoen never mind my babbling. My PR was failing a different test, and it should have. To fix the CI issue with this PR, do the following:

1) build your branch as usual
2) run build/bin/solvespace-testsuite
3) notice that it fails on constraint/angle/skew-render
4) open the folder:  test/constraint/angle
5) find files  "skew.out.png" and "skew.out".
6) delete "skew.out" and rename "skew.out.png" to "skew.out"
7) commit the change to your branch and push to you GH.

I have no idea which 12 pixels are different in those images or why this change causes it ;-)

**Comment by vespakoen** [comment]
For reference:

skew.out.png
skew out

skew.png
skew

skew.diff.png
skew diff

Looks like the segment is now underneath the point at X0 Y0.

I have updated the image so the test will pass.

**Comment by phkahler** [comment]
This PR is really really nice. Not only does it make selection better, it improves rendering when you do rounded corners for example. Thanks!

**Pull request merged**
