### PR TITLE
Permit toggling construction geometry while drawing lines

### PR DESCRIPTION
**Pull request by robnee**
This is for consideration for **post 3.0 release**

Currently attempting to toggle construction geometry while drawing line segments results in an error dialog.  This PR enables the construction geometry toggle command ('g' key) to work while drawing lines.  This does not affect other requests (but maybe it could)

I feel this is an improvement over the error dialog and is useful when sketching.  @phkahler I'm curious what you think of this.

### CODE REVIEW

**Comment by phkahler** [comment]
I like this idea a lot. It will reduce the need to re-select a line after its drawn to press G. It would be great to be able to do it while dragging new lines, arcs, rectangles.

@robnee when you updated your branch, this PR got the changes. It now has 5 commits. Fortunately we could still isolate the one you wanted for this PR.

**Comment by phkahler** [comment]
This works even better than I thought it would. When drawing multiple segments once you toggle it stays that way for the rest of them unless you toggle back!

**Comment by robnee** [comment]
Yes, sorry, I meant for that to only be a single commit.  I can resubmit if you need me to.  I can also try enabling it for other entities.

This started as simply suppressing the error dialog while drawing.  I frequently try to hit 'g' while drawing, never remembering it doesn't work.  It was very easy to take that and just make it work instead.

**Comment by phkahler** [comment]
I need to leave an unreleated note here, pretty sure it was a fluke and not related to this patch. I recently upgraded to Fedora 33 so maybe a new message? After testing this, my terminal window contained this new message:

Gdk-Message: 17:45:14.723: Window 0x1370d90 is a temporary window without parent, application will not be able to position it on screen.

(solvespace:99349): Gdk-CRITICAL **: 17:45:14.728: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed

Since I've never seen that, I stashed the changes and didn't get the message next time I ran. I want to  investigate more as it seems to relate to issue #797   No idea why it chose now to happen.

**Comment by robnee** [comment]
@phkahler Maybe this line causes the gtk issue you noticed?  I am not sure it's necessary for this to work.  I'll need to get my Linux build working anyway so I'll try this weekend.

SS.ScheduleShowTW();

**Comment by robnee** [comment]
@phkahler I haven't been able to reproduce this on Linux.  I don't really know GTK well but [this documentation ](https://valadoc.org/gtk+-3.0/Gtk.Window.set_transient_for.html) states:

>Dialog windows should be set transient for the main application window they were spawned from.
>This allows window managers to e.g. keep the dialog on top of the main window, or center the dialog over the main window. Dialog.with_buttons and other convenience functions in GTK+ will sometimes call set_transient_for on your behalf.

I see `set_transient_for` call being made for the two top-level windows (in CreateWindow) but not for MessageDialogs.

**Comment by robnee** [comment]
@phkahler I've also gotten this working for new rectangles, cubics, circles and arcs.

**Comment by phkahler** [comment]
> @phkahler I've also gotten this working for new rectangles, cubics, circles and arcs.

@robnee  Nice!  Can you make a clean PR from it or unclog this one?

**Comment by phkahler** [comment]
Replaced by #923. Closing.

**Pull request closed without merging**
