### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nii236**
After spending a weekend trying to get the code to compile from Windows for Windows, I ended up going with WSL and after some time managed to get it compiling. 

I've updated the instructions to help anyone else in my situation.

### CODE REVIEW

**Comment by phkahler** [comment]
Seems slightly Ubuntu-centric, are you sure about 20.04 as requirement?

Also why remove the 32bit instructions and only tell people to build 64bit? Our released Windows builds are actually 32bit.

**Comment by nii236** [comment]
Ubuntu 18.04 does not have libflatbuffers-dev available in apt, and the PPAs available weren't useful either. Instructions only worked for Ubuntu 20.04. I lost a weekend messing around with compilation instructions so I wanted to help save time for future people who may be entering this repo fresh.

32 bit compilation failed due to issues in:
```
./solvespace/extlib/angle/src/libANGLE/renderer/d3d/loadimageSSE2.cpp:50:48
```
The specific error was:
```
/usr/lib/gcc/i686-w64-mingw32/9.3-win32/include/emmintrin.h:1004:1: error: inlining failed in call to always_inline ‘__m128i _mm_unpacklo_epi8(__m128i, __m128i)’: target specific option mismatch
```

Compiling for 64bit worked without incident.

**Comment by kk6mrp** [comment]
Shouldn't the 32 bit commands be left for other distributions?

**Comment by nii236** [comment]
@kk6mrp then it needs to be clarified which ones work and which don't.

**Comment by phkahler** [comment]
@kk6mrp  The best way to build for Windows is to build ON windows, which has its own instructions. Cross compiling can be useful but we dont need to cover every case here, just enough to help people do it successfully.

**Comment by kk6mrp** [comment]
That is true but it seems a little more confusing now than before, maybe that is just me though.

**Pull request merged**
