### PR TITLE
UI: Non anti aliased icons for the graphics and text windows

### PR DESCRIPTION
**Pull request by ruevs**
Created by jkrei0 here https://github.com/jkrei0/solvespace

Optimized for size.

Merged all but `shaded.png` since in my opinion the current one is better.

Discussion here https://github.com/solvespace/solvespace/issues/857

### Update 2021-03-03
I updated many of the icons to be much closer to the original ones. I also replaced the `Nearest isometric view` icon with one that looks like our isometric view. `My New` below are the latest icons.

Toolbar:
| Old | My New | jkrei0 | 
| ------- | ------ | ------ |
| ToolbarOldIcons2 | ToolbarNewMyIconsIn3D | ToolbarNewIcons2 |

| Text windoiw |   |
| --- | --- |
| Old | TextWindowsrOldIcons2 |
| My New | TextWindowsrNewMyIcons |
| jkrei0 | TextWindowsrNewIcons2 |

### CODE REVIEW

**Comment by ruevs** [comment]
https://www.quora.com/Are-fonts-that-arent-anti-aliased-called-aliased-or-non-anti-aliased-or-something-else
Yes, I was thinking about this while writing the commit message :-D :-D

**Comment by phkahler** [comment]
There are actually a lot of these I don't like:
Circle and Arc look smaller.
The A in text looks IMO worse. The old one should just be brighter if it's not at 255 yet.
Toggle Construction looks smaller. An I imagining these as smaller?
Split - Not sure if there should be a point where they intersect. Leaning toward the new one is better.
Constrain point on line should have a point at the intersection. Or maybe the purple square should show up more?

The rest are good. I know there are more on the way too, so we'll get another pass at it.

One thing I dislike about the old ones is there are so many points. Individually I like the old icons, but as a collection all those green points look like clutter. These new one are better in that way.

The one that really really annoys me is the isometric view icon is not isometric. I know @Symbian9 has a new version of those two.

**Comment by ruevs** [comment]
in3d
Working on it. But AN isometric view can look like the current icon. Just not our `F3` 120° one.
For example open the attached file and press `W` ;-) Then press `F3`...
[IsometricViewVsOurIcon.zip](https://github.com/solvespace/solvespace/files/5826848/IsometricViewVsOurIcon.zip)

**Comment by phkahler** [comment]
> Do you want a pull request with just that icon?
> Shall we move the discussion back to #857 ?

Let's take it to #892

**Comment by Symbian9** [comment]
> There are actually a lot of these I don't like:

Yep, I see it too.

**Comment by ruevs** [comment]
@phkahler @jkrei0 @Symbian9 I updated the icons again. Please see above in the pull request description and let me know what you think.

**Comment by robnee** [comment]
I like the new isometric view icon.  I think it's easier to deduce its function and remember.

**Comment by Symbian9** [comment]
@ruevs, `../graphics-window/pointonx.png` has 3 black 'dummy' pixels which should be removed:

pic.1

**Comment by phkahler** [comment]
Only 2 comments. The stray black pixels pointed out above. And also, did you change the color of the red Xs to ( 240, 32, 32 )?

I'm not sure how to apply this to a local branch since I can't change the commits to patches and save them ;-)

**Comment by ruevs** [comment]
> @ruevs, some icons still needs cleanup:

Thanks for checking. Fixed. I also reviewed all others for transparency problems.

**Comment by ruevs** [comment]
> And also, did you change the color of the red Xs to ( 240, 32, 32 )?

@phkahler if you mean the X-es that cross out "disabled" icons in the text window - they are not bitmaps, they are drawn here:
https://github.com/solvespace/solvespace/blob/8c101d5f281ba670a3af2663302fe3dc7fb15283/src/textwin.cpp#L61
and they also have a transparency of 150, which can also be adjusted. If you want I'll make a separate pull request for this.,

**Comment by ruevs** [comment]
> I'm not sure how to apply this to a local branch since I can't change the commits to patches and save them ;-)

`git remote add ruevs https://github.com/ruevs/solvespace.git`
`git checkout ruevs/IconsFromjkrei0`

or

git rebase? https://git-scm.com/docs/git-rebase

**Pull request merged**
