### PR TITLE
Add a cmake option ENABLE_LTO for link time optimization on Release b…

### PR DESCRIPTION
**Pull request by phkahler**
…uilds.

LTO builds take significantly longer but produce smaller executables with better performance.

### CODE REVIEW

**Comment by whitequark** [comment]
I think the condition isn't useful; for example it prevents `RelWithDebInfo` builds from using LTO.

**Comment by phkahler** [comment]
@whitequark what would be better? When developing I prefer release builds, but LTO takes several minutes longer. I don't think we want it for CI builds.

**Comment by whitequark** [comment]
Just have no condition? When developing you should use two build trees to avoid spurious rebuilds, anyway.

**Comment by phkahler** [comment]
> Just have no condition? When developing you should use two build trees to avoid spurious rebuilds, anyway.

Do you really want it for CI? we already take too long there sometimes. Also, what would two build trees get me?

**Comment by whitequark** [comment]
> Do you really want it for CI? we already take too long there sometimes.

Well, you're adding an option, not unconditionally enabling LTO builds. On CI (and presumably by default) the option would be off.

**Comment by phkahler** [comment]
Got it, you meant just the inner condition. Done.

**Pull request merged**
