### PR TITLE
Eigen over master

### PR DESCRIPTION
**Pull request by Evil-Spirit**

### CODE REVIEW

**Comment by phkahler** [comment]
The CI build is failing because of missing dependency? What do I need? What version? and where should it live?

**Comment by Evil-Spirit** [comment]
I have no idea how to make CI happy. The problem is what I use Windows, but CI failed for linux. I have Ubuntu only as virtual machine, but have no time to deal with it.

**Comment by phkahler** [comment]
@Evil-Spirit  I was able to manually merge the 1st, 4th, and 5th changes listed above. That can be found here:
https://github.com/phkahler/solvespace/tree/solver-patches

I'm tempted to merge that to master if you're OK with that. They are performance related but don't involve Eigen.

**Comment by phkahler** [comment]
> I'm tempted to merge that to master if you're OK with that.

@jwesthues  or should I not do that? Merging mine would attribute them to me in the log.

**Comment by jwesthues** [comment]
I haven't reviewed in detail, but the commits make sense to me conceptually.

**Comment by 77maxikov** [comment]
Maybe switch https://github.com/RLovelett/eigen.git to https://gitlab.com/libeigen/eigen.git may help?

**Comment by phkahler** [comment]
> Maybe switch https://github.com/RLovelett/eigen.git to https://gitlab.com/libeigen/eigen.git may help?

@77maxikov  Yeah that link is returning a 404. @Evil-Spirit can you change that URL in CMakeLists.txt to the new eigen over at gitlab as shown in the previous comment and push that to your branch. It should automatically come here and trigger a new CI build.

**Pull request closed without merging**
