### PR TITLE
Flatpak ci

### PR DESCRIPTION
**Pull request by rpavlik**
Builds on #1022.

Right now it just does it in the "test" mode, not in the "CD" mode. Ideally we'd probably have commits on master auto-deploy to a solvespace nightly, and something on flathub soon called 3.0 (approximately-3.0-with-some-packaging-updates is not very catchy)

### CODE REVIEW

**Comment by phkahler** [comment]
@rpavlik is this OK to merge or will all CI builds fail?

**Comment by rpavlik** [comment]
It will all fail right now. I have to fix this up

**Comment by rpavlik** [comment]
yeah I haven't had time yet but I do have one working locally. I don't remember if others fixed up the one on flathub for me or not.

**Comment by froqstar** [comment]
Hi @rpavlik , could you kindly share an update for what is the current status/plan with the flatpak config? 
I currently see no way to install solvespace in Fedora apart from compiling from sources. Trying to build the flatpak on master doesn't work. 
Could you share your locally-working flatpak config here for people to try for themselves?

**Comment by ppd** [comment]
@froqstar You could use snaps on Fedora (https://snapcraft.io/docs/installing-snap-on-fedora). But I guess you've already considered this option and rejected it.

**Comment by froqstar** [comment]
I am a little embarassed, but current master actually builds fine as a flatpak if one actually checks out the git submodules as described in the build instructions :flushed: 
Thanks for your time and efforts!

Still doesn't run because of `Sorry, only UTF-8 locales are supported.` but that is another topic.

**Comment by rpavlik** [comment]
Yeah I was thinking what I had in here should work, I was pretty sure I built it locally. I did also start the process of submitting to flathub and I think they offered some improvements too.

**Comment by rpavlik** [comment]
Thanks to @tinywrkb and the reviewers for flathub, the manifest is a lot nicer now (and the one submitted to flathub is again an active pull request). Hopefully it actually works here in github actions too.

**Comment by rpavlik** [comment]
Updated metadata does depend on https://github.com/solvespace/solvespace-web/pull/36 getting merged to actually point somewhere useful.

**Comment by rpavlik** [comment]
Yay, the CI passed, so this is finally ready to merge once solvespace/solvespace-web#36 is merged!

**Comment by rpavlik** [comment]
Oke-doke, this should be ready to review and merge. It has the updates to the metadata arrived at during the flathub review process. I've also added a mention of flathub to the readme.

**Review by ruevs — COMMENTED** [review]
I can only comment on the white space clean up in the .sh files and the updates of [com.solvespace.SolveSpace.metainfo.xml.in](https://github.com/solvespace/solvespace/pull/1026/files/d343ce39ddb70e467e0d32bd0dfff10828d7a300#diff-31199d53849cc1ef1973fbef4bda58af33d686ef1981a3499fe391b89f67e9a3) :-)

They look good :-)

Should you squash the commits a bit?  Or you prefer to have the "gory details" in master for some reason?

**Comment by rpavlik** [comment]
Oh I can squash if you like. Probably easier to merge that way. I have a lot of projects, some do the squash merge for everything so I just forgot in this case. The gory details are not important in this case.

**Comment by ruevs** [comment]
@rpavlik Oh, I did not realize "[tinywrkb](https://github.com/rpavlik/solvespace/commits?author=tinywrkb)" contributed in addition to you. Squashed or not - in this case I am fine either way. And it is easy to squash when merging - up to you, or @phkahler

**Comment by rpavlik** [comment]
I can probably take care of squashing it at least some today, no worries - there are some nice atomic commits here, mixed with really crappy "I plan on squashing" ones from me 🤣. Yeah, @tinywrkb was the impetus for finishing this and a huge help in bringing the Flatpak stuff up to modern standards, their help was greatly appreciated. I'm very happy that we now have a package on Flathub and we'll be able to have an even simpler package for 3.2. If I get a chance, I'll look into doing a similar edge package as we have for Snaps.

**Comment by rpavlik** [comment]
OK, the commits are much prettier now. merge as-is or squash to a single commit as desired.

**Comment by ruevs** [comment]
Even though I am not on Linux, considering that the ["flathubbot" (that seems to be rather picky) approved this](https://github.com/flathub/flathub/pull/2392#issuecomment-1172704746) and that it is merged and [3.1 is already up on Flathub](https://flathub.org/apps/details/com.solvespace.SolveSpace) I'll merge this even though I don't really understand the contents of `pkg/flatpak/com.solvespace.SolveSpace.json`.

**Pull request merged**
