### PR TITLE
Evilspirit eigen over ryan buildsys

### PR DESCRIPTION
**Pull request by rpavlik**
This is the Eigen-related stuff from #721, but put over my Eigen work excluding my work in the system.cpp file (so most but not all of #432 ).  Builds on #1158 and #1155 

I also split out the "too many unknowns" removal and put it at the end, in case we want to keep a now-artificial limit.

No new leaks.

### CODE REVIEW

**Comment by rpavlik** [comment]
Hmm, something in there is making things slower, not sure what. No time to test today, already spent too much time on this :) I did manage to get a speed bump with #1160 (test suite from 5.0s to 4.9s) but still getting slower on my test model, not sure why.

**Comment by phkahler** [comment]
You've included the commits from #1158 in this. Can you remove those?

And thank you for doing all this!

**Comment by rpavlik** [comment]
Sure, guess I can split out a few of mine from here. The idea was that the build system in the original pr wasn't great, and all but one of my eigen changes were little "peephole" optimizations based on hotspots i saw when profiling 4 years ago 😅 we'll see when I get a chance, I did way more Solvespace work the past few days than I was supposed to

**Comment by rpavlik** [comment]
Oh, ok, so I got the PR's mixed up in my head. The changes in here are necessarily dependent on at least a few commits from #1158.  I did drop most of my (minimal) changes from #432 because I thought that's what you had asked for :facepalm: . I also dropped the "remove too-many-constraints" commit for now. In any case, this is now rebased, builds on #1158 and incorporates #1155 . Rebasing now to drop as much of #1158 as possible.

**Comment by rpavlik** [comment]
OK, the version of this with as little of #1158 as possible, is here: https://github.com/solvespace/solvespace/compare/master...rpavlik:evilspirit-eigen-over-ryan-buildsys-fewer-solver-changes  I could drop the first three commits of #1158 but the rest were built upon by this code.

**Comment by phkahler** [comment]
@rpavlik  Looks like the first 9 commits here conflict since they were merged in the previous PR. What's the best way to handle that?

**Comment by rpavlik** [comment]
Weird, must be squash merging or something. I'll just rebase this if you don't beat me to it.

**Comment by rpavlik** [comment]
OK, rebased!

**Comment by phkahler** [comment]
@rpavlik   Lets see how this goes ;-)

**Comment by phkahler** [comment]
@rpavlik  question, in testing I ran into "Too many unknowns". The define is still set at 1024, but I thought the code was modified to not have an actual limit.  Should we remove some checks, or increase the value?

BTW I made a long chain (snake) of connected rectangles much like evil_spirit showed in a video. This runs dramatically smoother when dragging it around.  ;-)

**Comment by phkahler** [comment]
Closes #225

**Comment by vespakoen** [comment]
This is an awesome way to start the year!! Happy new year everybody! Thanks @Evil-Spirit and @rpavlik for making this happen!!

**Comment by rpavlik** [comment]
Awesome, thanks! The limit is now artificial, but left in to avoid getting to a point of being unresponsive. We can increase the define for Max unknowns as we see fit. Probably double it if we're a lot smoother now.

**Comment by ruevs** [comment]
After the fact I code-reviewed this fairly carefully and it is fine! Thank you very much for cleaning in up, making the integration clean  and rebasing it @rpavlik and thank you very much @Evil-Spirit for writing it in the first place back in 2017 :-)

**Pull request merged**
