### PR TITLE
textwin: Ensure va_end() is always called in TextWindow::Printf()

### PR DESCRIPTION
**Pull request by lioncash**

### CODE REVIEW

**Comment by whitequark** [comment]
Hi @lioncash,

The reason I didn't merge this PR yet is that SolveSpace should have a CLA, but it doesn't yet. We have a draft in the works, but I haven't got a signoff from every relevant party yet, and beyond that, issues with my health prevented me from touching SolveSpace for the entire summer as well as accumulating a massive backlog.

Anyway, in about a month I expect that every outstanding PR should be merged and reviewed, and there will be significantly more activity in other areas of the project. See ya!

**Comment by lioncash** [comment]
Hey @whitequark,

> issues with my health prevented me from touching SolveSpace for the entire summer as well as accumulating a massive backlog.

That sucks, hopefully the recovery went well (or is going well, if still dealing with it).

> Anyway, in about a month I expect that every outstanding PR should be merged and reviewed, and there will be significantly more activity in other areas of the project. See ya!

Sounds good; thanks for the heads-up on the situation!

**Comment by whitequark** [comment]
Thank you for your contribution, and welcome. The SolveSpace project has a Contributor License Agreement; in order to merge your pull request, please sign it at https://cla-assistant.io/solvespace/solvespace. It will take only a small amount of your time.

**Comment by lioncash** [comment]
Alright, done; everything should be in order

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
