### PR TITLE
Try to use notarytool

### LINKED ISSUE #1407: CI, macOS: update action to use "notarytool" instead of "altool"
### System information

- **[sign-macos.sh](https://github.com/solvespace/solvespace/blob/e6565c81186966a1c1bd7242e410419e02eb2774/.github/scripts/sign-macos.sh)**
- macOS GitHub CI

### Update needed to the macOS signing script

The GitHub  [action](https://github.com/solvespace/solvespace/actions/runs/6163878591/job/16729285064) building the "edge" version of SolveSpace in the "[Build Release macOS](https://github.com/solvespace/solvespace/actions/runs/6163878591/job/16729285064#logs)", on the "Sign Build" step gives a  [warning about `altool` being deprecated](https://github.com/solvespace/solvespace/actions/runs/6163878591/job/16729285064#step:5:288) and advises that a new "notarytool" should be used to sign the software.

```
2023-09-12 20:06:52.704 *** Warning: altool has been deprecated for notarization and starting in late 2023 will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software. (-1030)
```

[sign-macos.sh](https://github.com/solvespace/solvespace/blob/master/.github/scripts/sign-macos.sh) should be updated to use this "notarytool".

### Additional information

https://github.com/solvespace/solvespace/pull/1400#issuecomment-1716208224

### PR DESCRIPTION
**Pull request by vespakoen**
Untested...

Should be fixing #1407

### CODE REVIEW

**Comment by phkahler** [comment]
@rpavlik  can you have a look?

**Comment by phkahler** [comment]
@vespakoen  It passes all the test, so just merge it and see what happens ;-)  We should get an edge build without warnings right?

**Comment by rpavlik** [comment]
Sorry, I have no modern mac experience since 10.6. but hey, if it passes, I am in favor of merge if it seems needed.

**Comment by vespakoen** [comment]
The tests don't run the notarytool thing, only the CD workflow does that.
I was going to merge this once I have some time on my hands so I can correct any problems if they should occur ;)

**Comment by phkahler** [comment]
> The tests don't run the notarytool thing, only the CD workflow does that.

@vespakoen and @ruevs  and @rpavlik  What do you think about getting a 3.2rc1 our soon? And wrapping up 3.2 before year end?

**Comment by ruevs** [comment]
It is a great idea. There is enough - especially in "SolveSpace scale" - for a new release. But I really, really want to fix these https://github.com/solvespace/solvespace/milestone/5 before a final 3.2. I've self assigned most of them but they are the typical "boring" stuff that I never feel like starting...

**Comment by phkahler** [comment]
> But I really, really want to fix these

Three of those are path issues with linked parts! 

I have at least one tweak I want to make too. Solvespace turned 10 this year as open source.

**Comment by ruevs** [comment]
> Solvespace turned 10 this year as open source.

And 15 as a program - the first commit 67139236fc0b63e06eaa1efa8fe0022df5612bd2 Tuesday 2008-03-25 02:02:13 -0800. And 16 if we count when @jwesthues released [SketchFlat](https://cq.cx/sketchflat.pl) (Oct 2007, Cambridge MA).

**Comment by phkahler** [comment]
@vespakoen can I nudge you to get this and any other mac stuff in order?  ;-)

**Comment by vespakoen** [comment]
I'll try to look into this after the weekend

**Comment by ruevs** [comment]
@vespakoen @phkahler the CI now fails on macOS entirely https://github.com/solvespace/solvespace/actions/runs/8725534390
I'll merge this - let's see if it works.

```
++ xcrun altool --notarization-info '' -u *** -p ***
+ progress='2024-04-17 16:56:15.551 *** Error: Failed to get notarization info.
2024-04-17 16:56:15.551 *** Error: Notarization of MacOS applications using altool has been decommissioned. Please use notarytool. See: https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool (-1031)'
Error: Process completed with exit code 1.
```

**Comment by ruevs** [comment]
@vespakoen Naaah it did not work. And the build time became 24m55s (from 12m1s before) - it builds everything twice ;-(
https://github.com/solvespace/solvespace/actions/runs/8727893435/job/23946718599

**Pull request merged**
