### PR TITLE
revised zh_CN.po

### PR DESCRIPTION
**Pull request by liuxilu**

### CODE REVIEW

**Comment by ruevs** [comment]
@liuxilu it seems like there are many updates to already translated messages. Can you - at least in general - describe the nature of your updates?

@youzhou2020 and @lomatus would you please review this pull request?

**Comment by liuxilu** [comment]
@ruevs As the title, it's a revision. The translation before has many unconsistency.

**Comment by ruevs** [comment]
@liuxilu  are you satisfied/finished with the update? Shall I merge it?

**Comment by liuxilu** [comment]
It's finished. Please merge it.

**Comment by liuxilu** [comment]
@ruevs It's finished. Please merge it.

**Pull request merged**
