### PR TITLE
Allow DXF import of 3D arcs and circles

### PR DESCRIPTION
**Pull request by johreh**
Extrusion direction (normal) of arcs and circles were not taken into
account when importing.

- Add method for calculating a quaternion from extrusion direction
  according to DXF arbitrary axis algorithm
- Add required workplanes for arcs not on XY origin plane
- Adjust addDimRadial and addDimDiametric to include normal when
  creating associated circle request

### CODE REVIEW

**Comment by johreh** [comment]
Fix for #629 
Not that it might be prudent to merge pull request https://github.com/solvespace/libdxfrw/pull/13 before this one since it otherwise won't import 3D circle-constraints correctly. It also makes it possible to remove the temporary copies in those methods.

**Comment by whitequark** [comment]
Code looks essentially reasonable, I'll take a closer look again later. Can you attach a few files you're testing this on?

**Comment by phkahler** [comment]
@johreh  As I recall this worked, but I am unable to compile locally after applying the patch now. Seems to be related to the libdxfrw  change, but that looks like it got merged. It passed the CI test though so I'm not sure what to make of the situation.

**Comment by johreh** [comment]
@phkahler I just tried rebuilding this rebased on top of latest master. I did not get any build errors.

@whitequark Oops, forgot about this. I'll try to find some of the files I used.

**Pull request merged**
