### PR TITLE
Emscripten: Fix to build with latest toolset, and merge recent commits

### PR DESCRIPTION
**Pull request by verylowfreq**
This PR
 - fixes for able to built with latest emscripten toolset, and
 - merges recent commits in the master branch.

Related PR: https://github.com/solvespace/solvespace/pull/419
This PR resolves the issue https://github.com/solvespace/solvespace/issues/1037

My build is hosted on GitHub Pages ( https://verylowfreq.github.io/experimental-solvespace-on-browser/ ).

## Details:

The changes of Emscripten toolset broke the code introduced in 4d7145a763e5c4198b7a348dbbd2f93ab701b8bf . This PR fixes it. 

My build environment info:
 - OS: Ubuntu Linux 22.04 x86_64 (on WSL2)
 - Emscripten SDK: 26a0dea0d3bbf616fa7f0a908e5b08aab406f7c4 (2022-08-01)
 - emcc: 3.1.18
 - clang: 14.0.0

src/platform/guihtml.cpp is based on, and src/CMakeList.txt is partialy picked up from https://github.com/zopieux/solvespace/tree/emscripten  (Thanks, @zopieux !)

This PR merges the commits from the master branch. The latest commit that merged is bc4244e0990af31ff326a72e2152fed662fca3e9 (2022-07-08).

No functional improvement or fix is included.

### CODE REVIEW

**Comment by phkahler** [comment]
@verylowfreq   So you 1) fixed the emscripten issues and 2) merged all the more recent commits from master into the emscripten branch.   Is that correct?

Github says it "cannot be rebased due to conflicts". Is it trying to treat this as a pull request to master rather than to the branch?

It would be best to fix emscripten and rebase to master, rather than merging 300 changes to the branch. But this is good progress.

**Comment by zopieux** [comment]
Thanks for taking that on! Glad my fork was useful.

**Comment by verylowfreq** [comment]
Thank you for comments!

@phkahler

> So you 1) fixed the emscripten issues and 2) merged all the more recent commits from master into the emscripten branch. Is that correct?

Yes. That's correct. (sorry for my poor English.)


> Github says it "cannot be rebased due to conflicts". Is it trying to treat this as a pull request to master rather than to the branch?
> It would be best to fix emscripten and rebase to master, rather than merging 300 changes to the branch.

I inteneded that this PR will be just merged to emscripten branch ("Rebase and merge" is not checked).

You intend that the changes in this PR should be merged to master branch, don't you ?

I made a private branch that can "Rebase and merge" against master branch. If this is better, I'll replace this PR.
https://github.com/verylowfreq/solvespace/tree/rebasetest-emscripten

How do you think ?

Sorry for that I'm not familier with GitHub's PR operation flow. If I made misundersting, please tell me.

> But this is good progress.

Thank you :smile:

**Comment by ruevs** [comment]
> I made a private branch that can "Rebase and merge" against master branch. If this is better, I'll replace this PR.
> https://github.com/verylowfreq/solvespace/tree/rebasetest-emscripten

@verylowfreq I am very glad to see someone picking up the Web version! Especially you implementing storing the settings in local storage of the browser is great!

As for how to merge the changes - I think that a cleaner approach would be to first rebase the existing port to master as it is (I did this here https://github.com/ruevs/solvespace/tree/emscripten) and then rebase your changes on top of it as a separate commit - I did this here https://github.com/ruevs/solvespace/tree/rebasetest-emscripten. I this way the resulting branch can be cleanly merged with both `master` and `emscripten`.

@phkahler if you agree with this then I can push my rebased original `emscripten` upstream and then can create and merge a pull request with the @verylowfreq changes.

@verylowfreq can you please test https://github.com/ruevs/solvespace/tree/rebasetest-emscripten since I do not have the Emscripten toolchain installed? Just in case I screwed up something while rebasing. Especially `src/CMakeLists.txt` I did not keep exactly since you had the `EMSCRIPTEN` section duplicated.

**Comment by ruevs** [comment]
It is also worth looking at the changes @vespakoen made [two years ago while rebasing](https://github.com/vespakoen/solvespace/commits/vespakoen-emscripten) https://github.com/vespakoen/solvespace/commit/91df00be073cc29ac04602ae8e9231beb521174a

**Comment by phkahler** [comment]
> As for how to merge the changes - I think that a cleaner approach would be to first rebase the existing port to master as it is (I did this here https://github.com/ruevs/solvespace/tree/emscripten) and then rebase your changes on top of it as a separate commit - I did this here https://github.com/ruevs/solvespace/tree/rebasetest-emscripten. I this way the resulting branch can be cleanly merged with both `master` and `emscripten`.
> 
> @phkahler if you agree with this then I can push my rebased original `emscripten` upstream and then can create and merge a pull request with the @verylowfreq changes.

Yeah, that sounds good. I makes sense for the emscripten version to be a minimal set of changes from master. Rebasing the branch should make it look like it was just created recently, and it will make it easy to merge it to master.

As for merging to master, I think it's a good idea so long as it doesn't complicate the existing CI/CD. This is definitely something to discuss.  The benefit of course is that the target shouldn't bit-rot like it did this time.

**Comment by verylowfreq** [comment]
@ruevs Thanks! I've tried to build rebasetest-emscripten in your repository and it worked with two fixes.

**Fix-1)** src/platform/html/emshell.html has the following conflict marker at the end of the file. 
```
<<<<<<< HEAD
 --></body></html><!--
=======
 --></body></html>
>>>>>>> 3bd48d42 (Add a very experimental Emscripten port.)
```
` --></body></html>` is correct.

**Fix-2)** Your src/CMakeList.txt looks broken. Emscripten build will try to include files for Gtk and build fails.
I couldn't find the duplicated section about `EMSCRIPTEN` you said, but I think that this CMake script block about `EMSCRIPTEN` has to be here: 
(In the if/elseif/else block that follows "# Platform-specific" comment) https://github.com/verylowfreq/solvespace/blob/3bd48d42d0891b37e40c53199ba35e9d9748aa83/src/CMakeLists.txt#L307-L349
Please use my src/CMakeList.txt.

**Comment by vespakoen** [comment]
@verylowfreq Thanks, this is awesome!

I tested out https://github.com/ruevs/solvespace/tree/rebasetest-emscripten and it worked really great!

Obviously some things are broken, but I think we should go ahead and merge those changes in and see if we can polish it up some more later.

What I noticed from a quick test:
- Getting stuff in and out is not working yet (load file / save / export)
- `font-family` for the menu's / modals could be better
- A (1px) seperator between the main view and the property browser would be great

Once this is merged I can take a look at hooking it up into CI to make it easily downloadable, and maybe automatically make a PR to the SolveSpace website repository and host it somewhere on the website.

**Comment by verylowfreq** [comment]
@vespakoen Thanks :smile:
I'm working in my fork to implement missing features and some of them are implemented partially. (These modifications is not included in this PR.) My latest emscripten build is hosted in my GitHub Pages https://verylowfreq.github.io/experimental-solvespace-on-browser/ .
We can now use SolveSpace roughly even on iPad's Safari with touch actions. (Not a comfotable but it works. Downloading/uploading files also looks working. Exporting is working but no way to download it yet.)
Font is the big problem for me. Window rendered by OpenGL and elements in HTML is too differ in Japanese font. I'm thinking how to resolve it. `font-family` will help but additional something would be needed (it's difficult to handle CJK-Kanji fonts).

I updated this PR.

 - Based on https://github.com/ruevs/solvespace/tree/rebasetest-emscripten
 - Add fix to critical issues:
   - Invalid cast in SettingsImplHtml::ThawFloat
     - In some situation, this made the value of "chord torelance" option zero and caused extrude error.
   - Enable optimization for avoiding "too many lolcals" error in Web-browser.
   - Update README
   - Fix merging error in CMakeLists and emshell.html

----

Oops, unintended conflicts... something wrong in my git operation. 

Sorry but if someone can, please pick my changes up and merge it. I have no idea to merge my changes to emscripten branch correctly. Starting on https://github.com/ruevs/solvespace/tree/rebasetest-emscripten, adding my latest 4 commits (commits with "FIX: ..." comment) should be ok, I believe.

**Comment by vespakoen** [comment]
@verylowfreq I looked into this today.

It looks like your `emscripten-develop` branch has more features in it than this PR does.

And it also already seems to be rebased correctly with the current master branch.

Is there any reason for not making a PR using that branch, because if not I think it would be better to make a PR using that branch?


Over here I am getting the following warnings

```
emcc: warning: please replace -g4 with -gsource-map [-Wdeprecated]
```

And this one:

```
emcc:WARNING: Wasm source map won't be usable in a browser without --source-map-base
```

I tried compiling using `-gsourcemap` and `--source-map-base` but it was a bit hard to setup and didn't really work.

However, without those flags / in the current state I was able to get a decent stack trace with the `Debug` mode and a fast build in `Release` mode so it seems to work all right, at least for me.

Lastly, when compiling you might want to turn off some features to speed up the build:

```shell
emcmake cmake \
    -DEMSCRIPTEN="ON" \
    -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
    -DENABLE_OPENMP="OFF" \
    -DENABLE_LTO="OFF" \
    -DENABLE_TESTS="OFF" \
    -DENABLE_CLI="OFF" \
    -DENABLE_COVERAGE="OFF" \
    ..
```

And you can use the `-j <NUM_CPUS>` flag on the emmake make command to parallelise it:

```shell
emmake make -j$(sysctl -n hw.logicalcpu)
```

Hope that helped ;)

**Comment by ruevs** [comment]
@verylowfreq your https://github.com/verylowfreq/solvespace/tree/emscripten-develop has GREAT progress! Save, open and touch gestures work! I trsted them superficially on Firefox on the 6 years old  Android 6 phone I am currently on.

I'll follow your https://verylowfreq.github.io/experimental-solvespace-on-browser/ and the branch closely.

At any point - when you decide it is in good enough _experimental_ shape let me know and I'll gladly merge your changes to master (if @phkahler does not mind).

**Comment by phkahler** [comment]
> At any point - when you decide it is in good enough _experimental_ shape let me know and I'll gladly merge your changes to master (if @phkahler does not mind).

Are you kidding? I opened #1037 pretty much asking for this ;-) @ruevs you are more than welcome to shepherd it in to master in an appropriate way.

**Comment by ruevs** [comment]
Oh and https://github.com/verylowfreq/solvespace/commits/feature-em-fileio has even more save/load work! I think this is what is up on the "live" page.

**Comment by verylowfreq** [comment]
This PR is just a rebasing to master with critical fix. After #1280 was merged , I'll make a new PR to add features that already implemented in my fork.

About my live page; at this time (bin-2022081301), the live page was built from "feature-em-fileio" because I forgot merging it into "emscripten-develop" branch.

**Comment by ruevs** [comment]
> This PR is just a rebasing to master with critical fix. After #1280 was merged , I'll make a new PR to add features that already implemented in my fork.

OK in this case I will merge into master a bit more detailed set of commits that leads to 1:1 equivalent tree to #1280. Before merging I'll try installing the emscripten SDK (on Windows) to be sure I am not merging something stupid again :-)

**Comment by ruevs** [comment]
@verylowfreq Rebased and merged in master here f7415048a5769c78fc4bb02afa426d101059374d

Feel free to open pull requests for the new features when you are ready.

**Comment by ruevs** [comment]
One problem I had with building on Windows is that the emscripten version would not link until I copied the whole `res` directory to mybuild directory (`buildweb\res`)

I suspect the problem is here https://github.com/solvespace/solvespace/blob/f7415048a5769c78fc4bb02afa426d101059374d/res/CMakeLists.txt#L94 but have not tried to fix it yet.

```
[1/1] Linking CXX executable bin\solvespace.html
FAILED: bin/solvespace.html
cmd.exe /C "cd . && C:\PAR\Projects\emsdk\emsdk\upstream\emscripten\em++.bat  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wfloat-conversion -Werror=switch -O3 -DNDEBUG -flto=thin  --bind --shell-file C:/PAR/Projects/Solvespace/git/src/platform/html/emshell.html --no-heap-copy -s ALLOW_MEMORY_GROWTH=1 -s WASM=1 -s ASYNCIFY=1 -s DYNCALLS=1 -s ASSERTIONS=1 -s TOTAL_STACK=33554432 -s TOTAL_MEMORY=134217728 --preload-file res/freedesktop/solvespace-48x48.png --preload-file res/banner.txt --preload-file res/icons/graphics-window/angle.png --preload-file res/icons/graphics-window/arc.png --preload-file res/icons/graphics-window/assemble.png --preload-file res/icons/graphics-window/bezier.png --preload-file res/icons/graphics-window/circle.png --preload-file res/icons/graphics-window/construction.png --preload-file res/icons/graphics-window/equal.png --preload-file res/icons/graphics-window/extrude.png --preload-file res/icons/graphics-window/helix.png --preload-file res/icons/graphics-window/horiz.png --preload-file res/icons/graphics-window/image.png --preload-file res/icons/graphics-window/in3d.png --preload-file res/icons/graphics-window/lathe.png --preload-file res/icons/graphics-window/length.png --preload-file res/icons/graphics-window/line.png --preload-file res/icons/graphics-window/ontoworkplane.png --preload-file res/icons/graphics-window/other-supp.png --preload-file res/icons/graphics-window/parallel.png --preload-file res/icons/graphics-window/perpendicular.png --preload-file res/icons/graphics-window/pointonx.png --preload-file res/icons/graphics-window/point.png --preload-file res/icons/graphics-window/rectangle.png --preload-file res/icons/graphics-window/ref.png --preload-file res/icons/graphics-window/revolve.png --preload-file res/icons/graphics-window/same-orientation.png --preload-file res/icons/graphics-window/sketch-in-3d.png --preload-file res/icons/graphics-window/sketch-in-plane.png --preload-file res/icons/graphics-window/step-rotate.png --preload-file res/icons/graphics-window/step-translate.png --preload-file res/icons/graphics-window/symmetric.png --preload-file res/icons/graphics-window/tangent-arc.png --preload-file res/icons/graphics-window/text.png --preload-file res/icons/graphics-window/trim.png --preload-file res/icons/graphics-window/vert.png --preload-file res/icons/text-window/constraint.png --preload-file res/icons/text-window/construction.png --preload-file res/icons/text-window/edges.png --preload-file res/icons/text-window/faces.png --preload-file res/icons/text-window/occluded-visible.png --preload-file res/icons/text-window/occluded-stippled.png --preload-file res/icons/text-window/occluded-invisible.png --preload-file res/icons/text-window/mesh.png --preload-file res/icons/text-window/normal.png --preload-file res/icons/text-window/outlines.png --preload-file res/icons/text-window/point.png --preload-file res/icons/text-window/shaded.png --preload-file res/icons/text-window/workplane.png --preload-file res/locales.txt --preload-file res/locales/cs_CZ.po --preload-file res/locales/de_DE.po --preload-file res/locales/en_US.po --preload-file res/locales/fr_FR.po --preload-file res/locales/uk_UA.po --preload-file res/locales/es_AR.po --preload-file res/locales/tr_TR.po --preload-file res/locales/ru_RU.po --preload-file res/locales/zh_CN.po --preload-file res/locales/ja_JP.po --preload-file res/fonts/unifont.hex.gz --preload-file res/fonts/private/0-check-false.png --preload-file res/fonts/private/1-check-true.png --preload-file res/fonts/private/2-radio-false.png --preload-file res/fonts/private/3-radio-true.png --preload-file res/fonts/private/4-stipple-dot.png --preload-file res/fonts/private/5-stipple-dash-long.png --preload-file res/fonts/private/6-stipple-dash.png --preload-file res/fonts/private/7-stipple-zigzag.png --preload-file res/fonts/unicode.lff.gz --preload-file res/fonts/BitstreamVeraSans-Roman-builtin.ttf --preload-file res/shaders/imesh.frag --preload-file res/shaders/imesh.vert --preload-file res/shaders/imesh_point.frag --preload-file res/shaders/imesh_point.vert --preload-file res/shaders/imesh_tex.frag --preload-file res/shaders/imesh_texa.frag --preload-file res/shaders/imesh_tex.vert --preload-file res/shaders/mesh.frag --preload-file res/shaders/mesh.vert --preload-file res/shaders/mesh_fill.frag --preload-file res/shaders/mesh_fill.vert --preload-file res/shaders/edge.frag --preload-file res/shaders/edge.vert --preload-file res/shaders/outline.vert --preload-file res/threejs/three-r111.min.js.gz --preload-file res/threejs/hammer-2.0.8.js.gz --preload-file res/threejs/SolveSpaceControls.js src/CMakeFiles/solvespace.dir/solvespace.cpp.o src/CMakeFiles/solvespace.dir/platform/entrygui.cpp.o src/CMakeFiles/solvespace.dir/render/gl3shader.cpp.o src/CMakeFiles/solvespace.dir/render/rendergl3.cpp.o src/CMakeFiles/solvespace.dir/platform/guihtml.cpp.o  -o bin\solvespace.html  bin/libsolvespace-core.a bin/libdxfrw.a bin/libpng16.a bin/libzlibstatic.a bin/libfreetype.a bin/libcairo.a bin/libpixman-1.a bin/libmimalloc.a -lpthread && cmd.exe /C "cd /D C:\PAR\Projects\Solvespace\git\buildweb\src && "C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different C:/PAR/Projects/Solvespace/git/src/platform/html/solvespaceui.css C:/PAR/Projects/Solvespace/git/buildweb/bin/solvespaceui.css && cd /D C:\PAR\Projects\Solvespace\git\buildweb\src && "C:\Program Files\CMake\bin\cmake.exe" -E copy_if_different C:/PAR/Projects/Solvespace/git/src/platform/html/solvespaceui.js C:/PAR/Projects/Solvespace/git/buildweb/bin/solvespaceui.js""
error: res/freedesktop/solvespace-48x48.png does not exist
em++: error: 'C:\PAR\Projects\emsdk\emsdk\upstream\emscripten\tools\file_packager.bat bin\solvespace.data --from-emcc --export-name=Module --preload res/freedesktop/solvespace-48x48.png res/banner.txt res/icons/graphics-window/angle.png res/icons/graphics-window/arc.png res/icons/graphics-window/assemble.png res/icons/graphics-window/bezier.png res/icons/graphics-window/circle.png res/icons/graphics-window/construction.png res/icons/graphics-window/equal.png res/icons/graphics-window/extrude.png res/icons/graphics-window/helix.png res/icons/graphics-window/horiz.png res/icons/graphics-window/image.png res/icons/graphics-window/in3d.png res/icons/graphics-window/lathe.png res/icons/graphics-window/length.png res/icons/graphics-window/line.png res/icons/graphics-window/ontoworkplane.png res/icons/graphics-window/other-supp.png res/icons/graphics-window/parallel.png res/icons/graphics-window/perpendicular.png res/icons/graphics-window/pointonx.png res/icons/graphics-window/point.png res/icons/graphics-window/rectangle.png res/icons/graphics-window/ref.png res/icons/graphics-window/revolve.png res/icons/graphics-window/same-orientation.png res/icons/graphics-window/sketch-in-3d.png res/icons/graphics-window/sketch-in-plane.png res/icons/graphics-window/step-rotate.png res/icons/graphics-window/step-translate.png res/icons/graphics-window/symmetric.png res/icons/graphics-window/tangent-arc.png res/icons/graphics-window/text.png res/icons/graphics-window/trim.png res/icons/graphics-window/vert.png res/icons/text-window/constraint.png res/icons/text-window/construction.png res/icons/text-window/edges.png res/icons/text-window/faces.png res/icons/text-window/occluded-visible.png res/icons/text-window/occluded-stippled.png res/icons/text-window/occluded-invisible.png res/icons/text-window/mesh.png res/icons/text-window/normal.png res/icons/text-window/outlines.png res/icons/text-window/point.png res/icons/text-window/shaded.png res/icons/text-window/workplane.png res/locales.txt res/locales/cs_CZ.po res/locales/de_DE.po res/locales/en_US.po res/locales/fr_FR.po res/locales/uk_UA.po res/locales/es_AR.po res/locales/tr_TR.po res/locales/ru_RU.po res/locales/zh_CN.po res/locales/ja_JP.po res/fonts/unifont.hex.gz res/fonts/private/0-check-false.png res/fonts/private/1-check-true.png res/fonts/private/2-radio-false.png res/fonts/private/3-radio-true.png res/fonts/private/4-stipple-dot.png res/fonts/private/5-stipple-dash-long.png res/fonts/private/6-stipple-dash.png res/fonts/private/7-stipple-zigzag.png res/fonts/unicode.lff.gz res/fonts/BitstreamVeraSans-Roman-builtin.ttf res/shaders/imesh.frag res/shaders/imesh.vert res/shaders/imesh_point.frag res/shaders/imesh_point.vert res/shaders/imesh_tex.frag res/shaders/imesh_texa.frag res/shaders/imesh_tex.vert res/shaders/mesh.frag res/shaders/mesh.vert res/shaders/mesh_fill.frag res/shaders/mesh_fill.vert res/shaders/edge.frag res/shaders/edge.vert res/shaders/outline.vert res/threejs/three-r111.min.js.gz res/threejs/hammer-2.0.8.js.gz res/threejs/SolveSpaceControls.js' failed (returned 1)
ninja: build stopped: subcommand failed.
```

**Comment by verylowfreq** [comment]
@ruevs 
I tested on Linux (on native machine and WSL2), so not tested on Windows console yet. I'll check it.

Thanks for reviewing and merging. I'm excited that SolveSpace will be used on various devices and situations. :smile:

**Comment by ruevs** [comment]
@verylowfreq take a look at the original pull request by @whitequark https://github.com/solvespace/solvespace/pull/419 - it has a ToDo list. But seeing that you already started scrollbars I suspect you are aware of it :-)

**Pull request closed without merging**
