### PR TITLE
Save stipple settings for default styles to config

### LINKED ISSUE #957: stipple width
Hi guys,

In the settings, "stipple width" is the area where the targeted element is selected right ?
When I modify it in the settings, it doesn't keep the setting saved, when I restart SolveSpace, it returns back to the default value (15).
All the other settings I modify are kept.

Any ideas ??

Thanks a lot...

Win 10 home 64

3.0RC2

### PR DESCRIPTION
**Pull request by robnee**
This PR saves the stipple settings for default styles to the configuration and closes #957.

### CODE REVIEW

**Comment by phkahler** [comment]
Does it fix #957?  You an link PRs to issues over on the right so merging will automatically close the issue if that's appropriate.

**Comment by robnee** [comment]
@phkahler Yes it does.  There was some additional discussion about import/export of default styles but that should be it's own issue.  Also, thanks for the tip on linking to issues!

**Comment by robnee** [comment]
@phkahler I linked to the issue using the "closes" keyword in the description.  I'm not sure if I can manually link it.  There is no gear icon on the RHS for me.  Is this something only available to the 4 SS members?

**Comment by ruevs** [comment]
> @phkahler I linked to the issue using the "closes" keyword in the description. I'm not sure if I can manually link it. There is no gear icon on the RHS for me. Is this something only available to the 4 SS members?

It's possible. I'm not sure. By the way there are 6, but two are have set their membership to "private" and I presume are not visible for non-members.

**Comment by phkahler** [comment]
> @phkahler I linked to the issue using the "closes" keyword in the description. I'm not sure if I can manually link it. There is no gear icon on the RHS for me. Is this something only available to the 4 SS members?

The sidebar is not visible to me on mobile, only desktop. And looking at repositories I have no rights to there is no gear. Can't find an options to enable it either :-(

**Comment by robnee** [comment]
I was able to link it by editing by initial comment and replacing the word "addresses" with "closes"  Seems GH looks for certain keywords.

**Comment by Symbian9** [comment]
@robnee, could you check, does latest commits in hidden style introduced incorrect default stipple type for `s00e-#def-hidden-edge` style:

- https://github.com/solvespace/solvespace/issues/1027#issuecomment-826293943

**Pull request merged**
