### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by ruevs**
https://github.com/solvespace/solvespace/issues/312#issuecomment-625856658

### CODE REVIEW

**Comment by Symbian9** [comment]
JFTR, Is there any info on 3dconnexion SpaceMouse support in SolveSpace 3.0 (`master`) under Linux?

**Comment by whitequark** [comment]
@ruevs There's a merge conflict in this PR. Also, do you think you could take a look at the commits since the previous changelog update to see if we've missed anything else?

@Symbian9 It works on Linux.

**Comment by phkahler** [comment]
When did native Wayland go in? Don't see it in the changelog.  I try not to run anything X these days.

**Comment by whitequark** [comment]
A long time ago: da7c74af2e678e471165d9142e8e3537af142e3a. It was mostly a side effect of migrating to GTK3.

**Comment by ruevs** [comment]
> 
> 
> @ruevs There's a merge conflict in this PR. Also, do you think you could take a look at the commits since the previous changelog update to see if we've missed anything else?

I updated the change-log with everything interesting since September 2019 https://github.com/solvespace/solvespace/pull/604

**Pull request closed without merging**
